import { getAuthRuntime, hashPassword, needsPasswordRehash, resendEmailVerification, sendEmailVerification, verifyPassword } from './runtime'
import { check, currentAccessToken, id, impersonate, impersonateById, impersonation, login, loginUsing, loginUsingId, logout, provider, refreshUser, register, requestPasswordReset, resetPassword, stopImpersonating, tokens, user, verification, verifyEmail } from './facade'
import type { AuthFacade } from './contracts'

export { AUTH_ERROR_CODES, AuthError, isAuthError } from './contracts'
export {
  defineAuthConfig,
  holoAuthDefaults,
  normalizeAuthConfig,
} from './config'
export type {
  AuthClerkProviderConfig,
  AuthEmailVerificationConfig,
  AuthHostedIdentityRecord,
  AuthHostedIdentityStore,
  AuthPasswordBrokerConfig,
  AuthPersonalAccessTokenConfig,
  AuthSocialProviderConfig,
  AuthWorkosProviderConfig,
  HoloAuthClerkConfig,
  HoloAuthWorkosConfig,
  NormalizedAuthClerkProviderConfig,
  NormalizedAuthGuardConfig,
  NormalizedAuthPasswordBrokerConfig,
  NormalizedAuthProviderConfig,
  NormalizedAuthSocialProviderConfig,
  NormalizedAuthWorkosProviderConfig,
  NormalizedHoloAuthClerkConfig,
  NormalizedHoloAuthWorkosConfig,
} from './config'
export {
  check,
  currentAccessToken,
  id,
  impersonate,
  impersonateById,
  impersonation,
  login,
  loginUsing,
  loginUsingId,
  logout,
  provider,
  refreshUser,
  register,
  requestPasswordReset,
  resetPassword,
  stopImpersonating,
  tokens,
  user,
  verification,
  verifyEmail,
} from './facade'
export {
  authRuntimeInternals,
  configureAuthRuntime,
  createAsyncAuthContext,
  getAuthRuntime,
  hashPassword,
  needsPasswordRehash,
  resendEmailVerification,
  resetAuthRuntime,
  sendEmailVerification,
  verifyPassword,
} from './runtime'
export type {
  AuthFailure,
  AuthenticatedAuthUser,
  AuthAuthorizable,
  AuthAuthorizationSubject,
  AuthAuthorizationTarget,
  AuthAuthorizationTargetConstructor,
  AuthAuthorizationTargetModel,
  AuthAuthorizationTargetModelDefinition,
  AuthClientConfig,
  AuthClientRequestOptions,
  AuthCredentials,
  AuthCurrentAccessToken,
  AuthDeliveryHook,
  AuthErrorCode,
  AuthEmailVerificationConsumeErrorCode,
  AuthEmailVerificationFacade,
  AuthEmailVerificationResendErrorCode,
  AuthEmailVerificationSendOptions,
  AuthEstablishedSession,
  AuthFacade,
  AuthBaseGuardFacade,
  AuthFieldErrors,
  AuthFailureResult,
  AuthGuardFacade,
  AuthGuardFacadeFor,
  AuthGuardLoginData,
  AuthGuardRegistrationData,
  AuthInputFieldErrors,
  AuthSessionGuardFacade,
  AuthSessionOnlyFacade,
  AuthImpersonationOptions,
  AuthImpersonationState,
  AuthLoginErrorCode,
  AuthLogoutResult,
  AuthSessionLoginOptions,
  AuthPasswordHasher,
  AuthPasswordResetInput,
  AuthPasswordResetConsumeErrorCode,
  AuthPasswordResetRequestInput,
  AuthPasswordResetRequestErrorCode,
  AuthPasswordResetRequestOptions,
  AuthRegistrationErrorCode,
  AuthResult,
  AuthSuccessResult,
  AuthTokenFacade,
  AuthTokenGuardFacade,
  AuthTokenStore,
  AuthUser,
  HoloAuthUser,
  AuthGuardConfig,
  AuthProviderConfig,
  AuthProviderAdapter,
  AuthRegistrationInput,
  AuthRuntimeBindings,
  AuthRuntimeAuthorization,
  AuthRuntimeContext,
  AuthUserLike,
  CurrentAuthResponse,
  EmailVerificationTokenRecord,
  EmailVerificationTokenResult,
  EmailVerificationTokenStore,
  HoloAuthTypeRegistry,
  HoloAuthConfig,
  AuthErrorOptions,
  NormalizedHoloAuthConfig,
  PersonalAccessTokenCreationOptions,
  PersonalAccessTokenRecord,
  PersonalAccessTokenResult,
  PasswordResetTokenRecord,
  PasswordResetTokenResult,
  PasswordResetTokenStore,
} from './contracts'

const auth: AuthFacade = Object.freeze({
  check,
  user,
  refreshUser,
  provider,
  id,
  currentAccessToken,
  hashPassword,
  login,
  loginUsing,
  loginUsingId,
  impersonate,
  impersonateById,
  impersonation,
  logout,
  needsPasswordRehash,
  register,
  requestPasswordReset,
  resendEmailVerification,
  resetPassword,
  sendEmailVerification,
  stopImpersonating,
  tokens,
  verification,
  verifyEmail,
  verifyPassword,
  guard<TName extends string>(name: TName) {
    return getAuthRuntime().guard(name)
  },
})

export default auth
