import { check, currentAccessToken, getAuthRuntime, hashPassword, id, impersonate, impersonateById, impersonation, login, loginUsing, loginUsingId, logout, needsPasswordRehash, refreshUser, register, requestPasswordReset, resendEmailVerification, resetPassword, sendEmailVerification, stopImpersonating, tokens, user, verification, verifyEmail, verifyPassword } from './runtime'

export { AUTH_ERROR_CODES, AuthError, defineAuthConfig, isAuthError } from './contracts'
export {
  authRuntimeInternals,
  check,
  configureAuthRuntime,
  createAsyncAuthContext,
  currentAccessToken,
  getAuthRuntime,
  hashPassword,
  id,
  impersonate,
  impersonateById,
  impersonation,
  login,
  loginUsing,
  loginUsingId,
  logout,
  needsPasswordRehash,
  refreshUser,
  register,
  requestPasswordReset,
  resendEmailVerification,
  resetAuthRuntime,
  resetPassword,
  sendEmailVerification,
  stopImpersonating,
  tokens,
  user,
  verification,
  verifyEmail,
  verifyPassword,
} from './runtime'
export type {
  AuthFailure,
  AuthClientConfig,
  AuthClientRequestOptions,
  AuthCredentials,
  AuthCurrentAccessToken,
  AuthDeliveryHook,
  AuthErrorCode,
  AuthEmailVerificationConsumeErrorCode,
  AuthEmailVerificationFacade,
  AuthEmailVerificationResendErrorCode,
  AuthEmailVerificationSendOptions,
  AuthEstablishedSession,
  AuthFacade,
  AuthFieldErrors,
  AuthFailureResult,
  AuthGuardFacade,
  AuthInputFieldErrors,
  AuthImpersonationOptions,
  AuthImpersonationState,
  AuthLoginErrorCode,
  AuthLogoutResult,
  AuthSessionLoginOptions,
  AuthPasswordHasher,
  AuthPasswordResetInput,
  AuthPasswordResetConsumeErrorCode,
  AuthPasswordResetRequestInput,
  AuthPasswordResetRequestErrorCode,
  AuthPasswordResetRequestOptions,
  AuthRegistrationErrorCode,
  AuthResult,
  AuthSuccessResult,
  AuthTokenFacade,
  AuthTokenStore,
  AuthUser,
  HoloAuthUser,
  AuthGuardConfig,
  AuthProviderConfig,
  AuthProviderAdapter,
  AuthRegistrationInput,
  AuthRuntimeBindings,
  AuthRuntimeContext,
  AuthUserLike,
  CurrentAuthResponse,
  EmailVerificationTokenRecord,
  EmailVerificationTokenResult,
  EmailVerificationTokenStore,
  HoloAuthTypeRegistry,
  HoloAuthConfig,
  AuthErrorOptions,
  NormalizedHoloAuthConfig,
  PersonalAccessTokenCreationOptions,
  PersonalAccessTokenRecord,
  PersonalAccessTokenResult,
  PasswordResetTokenRecord,
  PasswordResetTokenResult,
  PasswordResetTokenStore,
} from './contracts'

const auth = Object.freeze({
  check,
  user,
  refreshUser,
  id,
  currentAccessToken,
  hashPassword,
  login,
  loginUsing,
  loginUsingId,
  impersonate,
  impersonateById,
  impersonation,
  logout,
  needsPasswordRehash,
  register,
  requestPasswordReset,
  resendEmailVerification,
  resetPassword,
  sendEmailVerification,
  stopImpersonating,
  tokens,
  verification,
  verifyEmail,
  verifyPassword,
  guard(name: string) {
    return getAuthRuntime().guard(name)
  },
})

export default auth
