import { defineWorkspace } from 'vitest/config'

export default defineWorkspace([
  'packages/adapter-next',
  'packages/adapter-nuxt',
  'packages/adapter-sveltekit',
  'packages/auth',
  'packages/auth-clerk',
  'packages/auth-social',
  'packages/auth-social-google',
  'packages/auth-social-github',
  'packages/auth-social-discord',
  'packages/auth-social-facebook',
  'packages/auth-social-apple',
  'packages/auth-social-linkedin',
  'packages/auth-workos',
  'packages/config',
  'packages/db',
  'packages/events',
  'packages/forms',
  'packages/cli',
  'packages/core',
  'packages/media',
  'packages/queue',
  'packages/queue-db',
  'packages/session',
  'packages/storage',
  'packages/validation',
])
