import { mkdir, readFile, unlink, writeFile } from 'node:fs/promises'
import { dirname, resolve } from 'node:path'
import {
  GENERATED_SVELTE_HOOKS_PATH,
  GENERATED_SVELTE_SERVER_HOOKS_PATH,
} from './shared'
import {
  renderNextManagedHostedAuthRouteFiles,
  renderNextManagedRouteFiles,
} from './scaffold/framework-renderers'

function renderManagedSvelteHooksModule(): string {
  return [
    '// Generated by holo prepare. Do not edit.',
    '',
    'import type { Reroute } from \'@sveltejs/kit\'',
    'import { holoSvelteKitTransport } from \'@holo-js/adapter-sveltekit/transport\'',
    'import * as userHooks from \'../../src/hooks\'',
    '',
    'const universalHooks = userHooks as {',
    '  reroute?: Reroute',
    '  transport?: Partial<typeof holoSvelteKitTransport>',
    '}',
    '',
    'function normalizeStorageRoutePrefix(value: string | undefined): string {',
    '  const raw = value?.trim() ?? \'/storage\'',
    '  if (!raw || raw === \'/\') {',
    '    return \'/storage\'',
    '  }',
    '',
    '  return `/${raw.replace(/^\\/+|\\/+$/g, \'\')}`',
    '}',
    '',
    'function resolveStorageRoutePrefix(): string {',
    '  return normalizeStorageRoutePrefix(typeof process === \'undefined\' ? undefined : process.env.STORAGE_ROUTE_PREFIX)',
    '}',
    '',
    'export const reroute: Reroute = async (event) => {',
    '  const userPath = await universalHooks.reroute?.(event)',
    '  const pathname = typeof userPath === \'string\' ? userPath : event.url.pathname',
    '  const storageRoutePrefix = resolveStorageRoutePrefix()',
    '',
    '  if (storageRoutePrefix !== \'/storage\' && (pathname === storageRoutePrefix || pathname.startsWith(`${storageRoutePrefix}/`))) {',
    '    const suffix = pathname.slice(storageRoutePrefix.length)',
    '    return suffix ? `/storage${suffix}` : \'/storage\'',
    '  }',
    '',
    '  return userPath',
    '}',
    'export const transport = {',
    '  ...(universalHooks.transport ?? {}),',
    '  ...holoSvelteKitTransport,',
    '}',
    '',
  ].join('\n')
}

function renderManagedSvelteServerHooksModule(): string {
  return [
    '// Generated by holo prepare. Do not edit.',
    '',
    'import { error as svelteKitError, type Handle, type HandleFetch, type HandleServerError } from \'@sveltejs/kit\'',
    'import { adapterSvelteKitInternals, runWithSvelteKitRequestEvent } from \'@holo-js/adapter-sveltekit\'',
    'import { sequence } from \'@sveltejs/kit/hooks\'',
    'import { holo } from \'$lib/server/holo\'',
    'import * as userHooks from \'../../src/hooks.server\'',
    '',
    'const serverHooks = userHooks as {',
    '  handle?: Handle',
    '  handleError?: HandleServerError',
    '  handleFetch?: HandleFetch',
    '}',
    '',
    'function isHoloAuthorizationHttpError(cause: unknown): cause is Error & { readonly decision: { readonly status: 403 | 404 } } {',
    '  if (!(cause instanceof Error) || cause.name !== \'AuthorizationError\') {',
    '    return false',
    '  }',
    '',
    '  const decision = (cause as { readonly decision?: { readonly status?: unknown } }).decision',
    '  return decision?.status === 403 || decision?.status === 404',
    '}',
    '',
    'function serializeHoloValidationException(cause: unknown) {',
    '  return adapterSvelteKitInternals.serializeValidationException(cause) ?? null',
    '}',
    '',
    'const holoHandle: Handle = ({ event, resolve }) => runWithSvelteKitRequestEvent(event, async () => {',
    '  await holo.getApp()',
    '',
    '  try {',
    '    const response = await resolve(event)',
    '    return await adapterSvelteKitInternals.mapValidationActionResponse(event, response)',
    '  } catch (cause) {',
    '    if (isHoloAuthorizationHttpError(cause)) {',
    '      svelteKitError(cause.decision.status, cause.message)',
    '    }',
    '',
    '    const validationPayload = serializeHoloValidationException(cause)',
    '    if (validationPayload) {',
    '      if (adapterSvelteKitInternals.isApiEvent(event)) {',
    '        return Response.json(validationPayload, { status: validationPayload.status })',
    '      }',
    '',
    '      throw cause',
    '    }',
    '',
    '    throw cause',
    '  }',
    '})',
    '',
    'const holoHandleError: HandleServerError = async (input) => {',
    '  const validationPayload = serializeHoloValidationException(input.error)',
    '  if (validationPayload) {',
    '    adapterSvelteKitInternals.rememberValidationActionFailure(input.event, validationPayload)',
    '    return validationPayload',
    '  }',
    '',
    '  if (serverHooks.handleError) {',
    '    return await serverHooks.handleError(input)',
    '  }',
    '',
    '  return {',
    '    message: input.error instanceof Error ? input.error.message : \'Internal server error\',',
    '  }',
    '}',
    '',
    'export const handle = typeof serverHooks.handle === \'function\'',
    '  ? sequence(holoHandle, serverHooks.handle)',
    '  : holoHandle',
    'export const handleError = holoHandleError',
    'export const handleFetch = serverHooks.handleFetch',
    '',
  ].join('\n')
}

function renderSvelteDefaultHooksModule(): string {
  return [
    'export {}',
    '',
  ].join('\n')
}

function renderSvelteDefaultServerHooksModule(): string {
  return [
    'export {}',
    '',
  ].join('\n')
}

function isManagedPrepareArtifact(contents: string): boolean {
  return contents.startsWith('// Generated by holo prepare. Do not edit.')
}

function isLegacySvelteTransportHook(contents: string): boolean {
  return contents.trim() === [
    'import { holoSvelteKitTransport } from \'@holo-js/adapter-sveltekit/transport\'',
    '',
    'export const transport = holoSvelteKitTransport',
  ].join('\n').trim()
}

function isLegacySvelteServerHook(contents: string): boolean {
  return contents.trim() === [
    'import \'@holo-js/adapter-sveltekit\'',
    '',
    'import type { Handle } from \'@sveltejs/kit\'',
    'import { holo } from \'$lib/server/holo\'',
    '',
    'function normalizeStorageRoutePrefix(value: string | undefined): string {',
    '  const raw = value?.trim() ?? \'/storage\'',
    '  if (!raw || raw === \'/\') {',
    '    return \'/storage\'',
    '  }',
    '',
    '  return `/${raw.replace(/^\\/+|\\/+$/g, \'\')}`',
    '}',
    '',
    'export const handle: Handle = async ({ event, resolve }) => {',
    '  await holo.getApp()',
    '',
    '  const storageRoutePrefix = normalizeStorageRoutePrefix(process.env.STORAGE_ROUTE_PREFIX)',
    '',
    '  if (storageRoutePrefix !== \'/storage\') {',
    '    const pathname = event.url.pathname',
    '    if (pathname === storageRoutePrefix || pathname.startsWith(`${storageRoutePrefix}/`)) {',
    '      const suffix = pathname.slice(storageRoutePrefix.length)',
    '      event.url.pathname = suffix ? `/storage${suffix}` : \'/storage\'',
    '    }',
    '  }',
    '',
    '  return resolve(event)',
    '}',
  ].join('\n').trim()
}

async function readFileIfPresent(path: string): Promise<string | undefined> {
  try {
    return await readFile(path, 'utf8')
  } catch {
    return undefined
  }
}

async function unlinkIfPresent(path: string): Promise<void> {
  try {
    await unlink(path)
  } catch {
    // File does not exist or cannot be removed. Ignore.
  }
}

async function pathExists(path: string): Promise<boolean> {
  return (await readFileIfPresent(path)) !== undefined
}

const SVELTE_HOOKS_OVERRIDE_BLOCK = [
  '    files: {',
  '      hooks: {',
  '        server: \'.holo-js/generated/hooks.server\',',
  '        universal: \'.holo-js/generated/hooks\',',
  '      },',
  '    },',
].join('\n')
const SVELTE_CONFIG_WRAPPER_IMPORT = 'import { withHoloSvelteKit } from \'@holo-js/adapter-sveltekit/config\''
const LEGACY_SVELTE_PREPROCESS_IMPORT = 'import { holoSveltePreprocess } from \'@holo-js/adapter-sveltekit\''
const LEGACY_SVELTE_PREPROCESS_CALL = 'holoSveltePreprocess()'
const SVELTE_CONFIG_WRAPPER_CALL = 'withHoloSvelteKit('

function getSvelteConfigHooksOverrideState(contents: string): 'managed' | 'custom' | 'none' {
  if (contents.includes('.holo-js/generated/hooks')) {
    return 'managed'
  }

  if (/kit\s*:\s*\{[\s\S]*?files\s*:\s*\{[\s\S]*?hooks\s*:/.test(contents)) {
    return 'custom'
  }

  return 'none'
}

function assertSvelteConfigHasNoCustomHookOverride(contents: string): void {
  const hooksOverrideState = getSvelteConfigHooksOverrideState(contents)
  if (hooksOverrideState === 'custom') {
    throw new Error('Custom SvelteKit hook entrypoints are not supported. Remove kit.files.hooks from svelte.config.js and let holo prepare manage the generated hook bridge.')
  }
}

function ensureSvelteConfigWrapperImport(contents: string): string {
  if (contents.includes(SVELTE_CONFIG_WRAPPER_IMPORT)) {
    return contents
  }

  const lastImport = [...contents.matchAll(/^import .+$/gm)].at(-1)
  if (!lastImport || lastImport.index === undefined) {
    return `${SVELTE_CONFIG_WRAPPER_IMPORT}\n${contents}`
  }

  const insertAt = lastImport.index + lastImport[0].length
  return `${contents.slice(0, insertAt)}\n${SVELTE_CONFIG_WRAPPER_IMPORT}${contents.slice(insertAt)}`
}

function removeLegacySvelteConfigWiring(contents: string): string {
  return contents
    .replace(`${LEGACY_SVELTE_PREPROCESS_IMPORT}\n`, '')
    .replace(new RegExp(String.raw`,\s*${LEGACY_SVELTE_PREPROCESS_CALL.replace(/[.*+?^${}()|[\]\\]/g, '\\$&')}`, 'g'), '')
    .replace(new RegExp(String.raw`${LEGACY_SVELTE_PREPROCESS_CALL.replace(/[.*+?^${}()|[\]\\]/g, '\\$&')}\s*,\s*`, 'g'), '')
    .replace(`${SVELTE_HOOKS_OVERRIDE_BLOCK}\n`, '')
}

function patchSvelteConfigWithHoloWrapper(contents: string): string | undefined {
  assertSvelteConfigHasNoCustomHookOverride(contents)

  const cleaned = ensureSvelteConfigWrapperImport(removeLegacySvelteConfigWiring(contents))
  if (cleaned.includes(SVELTE_CONFIG_WRAPPER_CALL)) {
    return cleaned === contents ? undefined : cleaned
  }

  const constConfigPattern = /(const\s+config\s*=\s*)\{/
  if (!constConfigPattern.test(cleaned)) {
    throw new Error('Could not patch svelte.config.js with withHoloSvelteKit(). Export a const config object so holo prepare can manage the SvelteKit integration.')
  }

  const wrappedOpening = cleaned.replace(constConfigPattern, `$1${SVELTE_CONFIG_WRAPPER_CALL}{`)
  const wrapped = wrappedOpening.replace(/\}\s*export\s+default\s+config\s*$/u, '})\n\nexport default config')
  if (wrapped === wrappedOpening) {
    throw new Error('Could not patch svelte.config.js with withHoloSvelteKit(). Export a const config object so holo prepare can manage the SvelteKit integration.')
  }

  return wrapped
}

async function ensureSvelteConfigHooksOverride(projectRoot: string): Promise<void> {
  const configPath = resolve(projectRoot, 'svelte.config.js')
  const contents = await readFileIfPresent(configPath)
  if (!contents) {
    return
  }

  const patched = patchSvelteConfigWithHoloWrapper(contents) ?? contents
  if (patched !== contents) {
    await writeFile(configPath, patched, 'utf8')
  }
}

async function writeFileIfChanged(path: string, contents: string): Promise<void> {
  if ((await readFileIfPresent(path)) === contents) {
    return
  }

  await mkdir(dirname(path), { recursive: true })
  await writeFile(path, contents, 'utf8')
}

async function ensureSvelteManagedHooks(projectRoot: string): Promise<void> {
  const hooksPath = resolve(projectRoot, 'src/hooks.ts')
  const hooksServerPath = resolve(projectRoot, 'src/hooks.server.ts')
  const generatedHooksPath = resolve(projectRoot, GENERATED_SVELTE_HOOKS_PATH)
  const generatedServerHooksPath = resolve(projectRoot, GENERATED_SVELTE_SERVER_HOOKS_PATH)
  const legacyHooksUserPath = resolve(projectRoot, 'src/hooks.user.ts')
  const legacyHooksServerUserPath = resolve(projectRoot, 'src/hooks.server.user.ts')
  const [hooksContents, hooksServerContents, legacyUserContents, legacyServerUserContents] = await Promise.all([
    readFileIfPresent(hooksPath),
    readFileIfPresent(hooksServerPath),
    readFileIfPresent(legacyHooksUserPath),
    readFileIfPresent(legacyHooksServerUserPath),
  ])

  if (legacyUserContents && (!hooksContents || isManagedPrepareArtifact(hooksContents))) {
    await writeFileIfChanged(hooksPath, legacyUserContents)
    await unlinkIfPresent(legacyHooksUserPath)
  } else if (legacyUserContents && hooksContents === legacyUserContents) {
    await unlinkIfPresent(legacyHooksUserPath)
  }

  if (legacyServerUserContents && (!hooksServerContents || isManagedPrepareArtifact(hooksServerContents))) {
    await writeFileIfChanged(hooksServerPath, legacyServerUserContents)
    await unlinkIfPresent(legacyHooksServerUserPath)
  } else if (legacyServerUserContents && hooksServerContents === legacyServerUserContents) {
    await unlinkIfPresent(legacyHooksServerUserPath)
  }

  const currentHooks = await readFileIfPresent(hooksPath)
  if (!currentHooks || isManagedPrepareArtifact(currentHooks) || isLegacySvelteTransportHook(currentHooks)) {
    await writeFileIfChanged(hooksPath, renderSvelteDefaultHooksModule())
  }

  const currentServerHooks = await readFileIfPresent(hooksServerPath)
  if (!currentServerHooks || isManagedPrepareArtifact(currentServerHooks) || isLegacySvelteServerHook(currentServerHooks)) {
    await writeFileIfChanged(hooksServerPath, renderSvelteDefaultServerHooksModule())
  }

  await writeFileIfChanged(generatedHooksPath, renderManagedSvelteHooksModule())
  await writeFileIfChanged(generatedServerHooksPath, renderManagedSvelteServerHooksModule())
  await ensureSvelteConfigHooksOverride(projectRoot)
}

async function ensureNextManagedRoutes(projectRoot: string): Promise<void> {
  const authEnabled = await pathExists(resolve(projectRoot, 'app/api/auth/user/route.ts'))
  const storageEnabled = await pathExists(resolve(projectRoot, 'app/storage/[[...path]]/route.ts'))
  const broadcastAuthEnabled = await pathExists(resolve(projectRoot, 'app/broadcasting/auth/route.ts'))
  const clerkEnabled = await pathExists(resolve(projectRoot, 'app/api/auth/clerk/login/route.ts'))
  const workosEnabled = await pathExists(resolve(projectRoot, 'app/api/auth/workos/login/route.ts'))
  const files = [
    ...renderNextManagedRouteFiles({
      authEnabled,
      storageEnabled,
      broadcastAuthEnabled,
    }),
    ...renderNextManagedHostedAuthRouteFiles({
      clerk: clerkEnabled,
      workos: workosEnabled,
    }),
  ]

  for (const file of files) {
    await writeFileIfChanged(resolve(projectRoot, file.path), file.contents)
  }
}

export async function syncManagedFrameworkArtifacts(projectRoot: string): Promise<void> {
  let manifest: { framework?: string }
  try {
    const content = await readFile(resolve(projectRoot, '.holo-js/framework/project.json'), 'utf8')
    manifest = JSON.parse(content) as { framework?: string }
  } catch {
    return
  }

  if (manifest.framework === 'sveltekit') {
    await ensureSvelteManagedHooks(projectRoot)
  }

  if (manifest.framework === 'next') {
    await ensureNextManagedRoutes(projectRoot)
  }
}
