import { mkdir, readFile, readdir, unlink, writeFile } from 'node:fs/promises'
import { dirname, extname, join, resolve } from 'node:path'
import { loadConfigDirectory } from '@holo-js/config'
import { DEFAULT_HOLO_PROJECT_PATHS } from '@holo-js/db'
import { relativeImportPath } from '../templates'
import { importProjectModule } from './runtime'
import {
  GENERATED_AUTHORIZATION_REGISTRY_PATH,
  GENERATED_AUTHORIZATION_TYPES_PATH,
  CONFIG_EXTENSION_PRIORITY,
  GENERATED_COMMANDS_PATH,
  GENERATED_BROADCAST_PATH,
  GENERATED_BROADCAST_MANIFEST_PATH,
  GENERATED_BROADCAST_TYPES_PATH,
  GENERATED_CHANNELS_PATH,
  GENERATED_CONFIG_TYPES_PATH,
  GENERATED_EVENT_TYPES_PATH,
  GENERATED_EVENTS_PATH,
  GENERATED_GITIGNORE_PATH,
  GENERATED_INDEX_PATH,
  GENERATED_JOBS_PATH,
  GENERATED_LISTENERS_PATH,
  GENERATED_METADATA_PATH,
  GENERATED_MIGRATIONS_PATH,
  GENERATED_MODELS_PATH,
  GENERATED_QUEUE_TYPES_PATH,
  GENERATED_REGISTRY_JSON_PATH,
  GENERATED_ROOT,
  GENERATED_SEEDERS_PATH,
  GENERATED_SVELTE_HOOKS_PATH,
  GENERATED_SVELTE_SERVER_HOOKS_PATH,
  GENERATED_TSCONFIG_PATH,
  SUPPORTED_CONFIG_EXTENSIONS,
  type GeneratedBroadcastRegistryEntry,
  type GeneratedAuthorizationAbilityRegistryEntry,
  type GeneratedAuthorizationPolicyRegistryEntry,
  type GeneratedChannelRegistryEntry,
  type GeneratedEventRegistryEntry,
  type GeneratedJobRegistryEntry,
  type GeneratedListenerRegistryEntry,
  type GeneratedProjectRegistry,
  isRecord,
  makeProjectRelativePath,
  pathExists,
} from './shared'

export function renderGeneratedModule(exportName: string, value: unknown): string {
  return [
    '// Generated by holo prepare. Do not edit.',
    '',
    `export const ${exportName} = ${JSON.stringify(value, null, 2)}`,
    '',
    `export default ${exportName}`,
    '',
  ].join('\n')
}

export function renderGeneratedIndexModule(): string {
  return [
    '// Generated by holo prepare. Do not edit.',
    '',
    '/* eslint-disable @typescript-eslint/triple-slash-reference */',
    '',
    '/// <reference path="./broadcast.d.ts" />',
    '/// <reference path="./authorization/types.d.ts" />',
    '/// <reference path="./config.d.ts" />',
    '/// <reference path="./events.d.ts" />',
    '/// <reference path="./queue.d.ts" />',
    '',
    'import metadata from \'./metadata\'',
    'import models from \'./models\'',
    'import migrations from \'./migrations\'',
    'import seeders from \'./seeders\'',
    'import commands from \'./commands\'',
    'import jobs from \'./jobs\'',
    'import events from \'./events\'',
    'import listeners from \'./listeners\'',
    'import broadcast from \'./broadcast\'',
    'import channels from \'./channels\'',
    'import authorization from \'./authorization/registry\'',
    'import broadcastManifest from \'./broadcast-manifest\'',
    '',
    'export { metadata, models, migrations, seeders, commands, jobs, events, listeners, broadcast, channels, authorization, broadcastManifest }',
    '',
    'export const registry = {',
    '  ...metadata,',
    '  models,',
    '  migrations,',
    '  seeders,',
    '  commands,',
    '  jobs,',
    '  events,',
    '  listeners,',
    '  broadcast,',
    '  channels,',
    '  authorizationPolicies: authorization.policies,',
    '  authorizationAbilities: authorization.abilities,',
    '  broadcastManifest,',
    '}',
    '',
    'export default registry',
    '',
  ].join('\n')
}

function renderManagedSvelteHooksModule(): string {
  return [
    '// Generated by holo prepare. Do not edit.',
    '',
    'import type { Reroute } from \'@sveltejs/kit\'',
    'import { holoSvelteKitTransport } from \'@holo-js/adapter-sveltekit/transport\'',
    'import * as userHooks from \'../../src/hooks\'',
    '',
    'const universalHooks = userHooks as {',
    '  reroute?: Reroute',
    '  transport?: Partial<typeof holoSvelteKitTransport>',
    '}',
    '',
    'export const reroute = universalHooks.reroute',
    'export const transport = {',
    '  ...(universalHooks.transport ?? {}),',
    '  ...holoSvelteKitTransport,',
    '}',
    '',
  ].join('\n')
}

function renderManagedSvelteServerHooksModule(): string {
  return [
    '// Generated by holo prepare. Do not edit.',
    '',
    'import \'@holo-js/adapter-sveltekit\'',
    '',
    'import type { Handle, HandleFetch, HandleServerError } from \'@sveltejs/kit\'',
    'import { sequence } from \'@sveltejs/kit/hooks\'',
    'import { holo } from \'$lib/server/holo\'',
    'import * as userHooks from \'../../src/hooks.server\'',
    '',
    'const serverHooks = userHooks as {',
    '  handle?: Handle',
    '  handleError?: HandleServerError',
    '  handleFetch?: HandleFetch',
    '}',
    '',
    'function normalizeStorageRoutePrefix(value: string | undefined): string {',
    '  const raw = value?.trim() ?? \'/storage\'',
    '  if (!raw || raw === \'/\') {',
    '    return \'/storage\'',
    '  }',
    '',
    '  return `/${raw.replace(/^\\/+|\\/+$/g, \'\')}`',
    '}',
    '',
    'const holoHandle: Handle = async ({ event, resolve }) => {',
    '  await holo.getApp()',
    '',
    '  const storageRoutePrefix = normalizeStorageRoutePrefix(process.env.STORAGE_ROUTE_PREFIX)',
    '',
    '  if (storageRoutePrefix !== \'/storage\') {',
    '    const pathname = event.url.pathname',
    '    if (pathname === storageRoutePrefix || pathname.startsWith(`${storageRoutePrefix}/`)) {',
    '      const suffix = pathname.slice(storageRoutePrefix.length)',
    '      event.url.pathname = suffix ? `/storage${suffix}` : \'/storage\'',
    '    }',
    '  }',
    '',
    '  return resolve(event)',
    '}',
    '',
    'export const handle = typeof serverHooks.handle === \'function\'',
    '  ? sequence(holoHandle, serverHooks.handle)',
    '  : holoHandle',
    'export const handleError = serverHooks.handleError',
    'export const handleFetch = serverHooks.handleFetch',
    '',
  ].join('\n')
}

function renderSvelteDefaultHooksModule(): string {
  return [
    'export {}',
    '',
  ].join('\n')
}

function renderSvelteDefaultServerHooksModule(): string {
  return [
    'export {}',
    '',
  ].join('\n')
}

function isManagedPrepareArtifact(contents: string): boolean {
  return contents.startsWith('// Generated by holo prepare. Do not edit.')
}

function isLegacySvelteTransportHook(contents: string): boolean {
  return contents.trim() === [
    'import { holoSvelteKitTransport } from \'@holo-js/adapter-sveltekit/transport\'',
    '',
    'export const transport = holoSvelteKitTransport',
  ].join('\n').trim()
}

function isLegacySvelteServerHook(contents: string): boolean {
  return contents.trim() === [
    'import \'@holo-js/adapter-sveltekit\'',
    '',
    'import type { Handle } from \'@sveltejs/kit\'',
    'import { holo } from \'$lib/server/holo\'',
    '',
    'function normalizeStorageRoutePrefix(value: string | undefined): string {',
    '  const raw = value?.trim() ?? \'/storage\'',
    '  if (!raw || raw === \'/\') {',
    '    return \'/storage\'',
    '  }',
    '',
    '  return `/${raw.replace(/^\\/+|\\/+$/g, \'\')}`',
    '}',
    '',
    'export const handle: Handle = async ({ event, resolve }) => {',
    '  await holo.getApp()',
    '',
    '  const storageRoutePrefix = normalizeStorageRoutePrefix(process.env.STORAGE_ROUTE_PREFIX)',
    '',
    '  if (storageRoutePrefix !== \'/storage\') {',
    '    const pathname = event.url.pathname',
    '    if (pathname === storageRoutePrefix || pathname.startsWith(`${storageRoutePrefix}/`)) {',
    '      const suffix = pathname.slice(storageRoutePrefix.length)',
    '      event.url.pathname = suffix ? `/storage${suffix}` : \'/storage\'',
    '    }',
    '  }',
    '',
    '  return resolve(event)',
    '}',
  ].join('\n').trim()
}

async function readFileIfPresent(path: string): Promise<string | undefined> {
  try {
    return await readFile(path, 'utf8')
  } catch {
    return undefined
  }
}

async function unlinkIfPresent(path: string): Promise<void> {
  try {
    await unlink(path)
  } catch {
    // File does not exist or cannot be removed. Ignore.
  }
}

const SVELTE_HOOKS_OVERRIDE_BLOCK = [
  '    files: {',
  '      hooks: {',
  '        server: \'.holo-js/generated/hooks.server\',',
  '        universal: \'.holo-js/generated/hooks\',',
  '      },',
  '    },',
].join('\n')

function svelteConfigHasHooksOverride(contents: string): boolean {
  return contents.includes('.holo-js/generated/hooks')
}

function patchSvelteConfigWithHooksOverride(contents: string): string | undefined {
  if (svelteConfigHasHooksOverride(contents)) {
    return undefined
  }

  // Try to inject the files.hooks block right after `kit: {` (with possible trailing content on the same line).
  // Handle both multi-line `kit: {\n...` and single-line `kit: {}` or files without trailing newline.
  const patched = contents.replace(
    /(kit:\s*\{)([^\n]*\n?)/,
    (match, opening: string, rest: string) => {
      const trimmedRest = rest.trimEnd()
      // Single-line `kit: {}` — inject before the closing brace
      if (trimmedRest === '}' || trimmedRest === '},') {
        const suffix = trimmedRest.endsWith(',') ? ',' : ''
        return `${opening}\n${SVELTE_HOOKS_OVERRIDE_BLOCK}\n  }${suffix}\n`
      }
      return `${opening}${rest}${SVELTE_HOOKS_OVERRIDE_BLOCK}\n`
    },
  )

  return patched !== contents ? patched : undefined
}

async function ensureSvelteConfigHooksOverride(projectRoot: string): Promise<void> {
  const configPath = resolve(projectRoot, 'svelte.config.js')
  const contents = await readFileIfPresent(configPath)
  if (!contents) {
    return
  }

  const patched = patchSvelteConfigWithHooksOverride(contents)
  if (patched) {
    await writeFile(configPath, patched, 'utf8')
  }
}

async function ensureSvelteManagedHooks(projectRoot: string): Promise<void> {
  const hooksPath = resolve(projectRoot, 'src/hooks.ts')
  const hooksServerPath = resolve(projectRoot, 'src/hooks.server.ts')
  const generatedHooksPath = resolve(projectRoot, GENERATED_SVELTE_HOOKS_PATH)
  const generatedServerHooksPath = resolve(projectRoot, GENERATED_SVELTE_SERVER_HOOKS_PATH)

  // Migration: move content from old .user.ts files back to standard locations if present.
  const legacyHooksUserPath = resolve(projectRoot, 'src/hooks.user.ts')
  const legacyHooksServerUserPath = resolve(projectRoot, 'src/hooks.server.user.ts')
  const [hooksContents, hooksServerContents, legacyUserContents, legacyServerUserContents] = await Promise.all([
    readFileIfPresent(hooksPath),
    readFileIfPresent(hooksServerPath),
    readFileIfPresent(legacyHooksUserPath),
    readFileIfPresent(legacyHooksServerUserPath),
  ])

  // If the old .user.ts files exist, migrate their content to the standard hook paths
  // and delete the legacy files.
  if (legacyUserContents && (!hooksContents || isManagedPrepareArtifact(hooksContents))) {
    await writeFileIfChanged(hooksPath, legacyUserContents)
  }
  await unlinkIfPresent(legacyHooksUserPath)

  if (legacyServerUserContents && (!hooksServerContents || isManagedPrepareArtifact(hooksServerContents))) {
    await writeFileIfChanged(hooksServerPath, legacyServerUserContents)
  }
  await unlinkIfPresent(legacyHooksServerUserPath)

  // If the current src/hooks.ts is a legacy Holo-managed artifact or doesn't exist,
  // replace it with a clean default so the user owns the file.
  const currentHooks = await readFileIfPresent(hooksPath)
  if (!currentHooks || isManagedPrepareArtifact(currentHooks) || isLegacySvelteTransportHook(currentHooks)) {
    await writeFileIfChanged(hooksPath, renderSvelteDefaultHooksModule())
  }

  const currentServerHooks = await readFileIfPresent(hooksServerPath)
  if (!currentServerHooks || isManagedPrepareArtifact(currentServerHooks) || isLegacySvelteServerHook(currentServerHooks)) {
    await writeFileIfChanged(hooksServerPath, renderSvelteDefaultServerHooksModule())
  }

  // Write the Holo-managed hooks into the generated directory.
  await writeFileIfChanged(generatedHooksPath, renderManagedSvelteHooksModule())
  await writeFileIfChanged(generatedServerHooksPath, renderManagedSvelteServerHooksModule())

  // Ensure svelte.config.js points SvelteKit at the generated hook entrypoints.
  await ensureSvelteConfigHooksOverride(projectRoot)
}

async function syncManagedFrameworkArtifacts(projectRoot: string): Promise<void> {
  try {
    const content = await readFile(resolve(projectRoot, '.holo-js/framework/project.json'), 'utf8')
    const manifest = JSON.parse(content) as { framework?: string }

    if (manifest.framework === 'sveltekit') {
      await ensureSvelteManagedHooks(projectRoot)
    }
  } catch {
    // Ignore missing or invalid framework manifests during registry writes.
  }
}

function renderAugmentationInterface(
  name: string,
  members: readonly string[],
): string[] {
  if (members.length === 0) {
    return [
      '  // eslint-disable-next-line @typescript-eslint/no-empty-object-type',
      `  interface ${name} {}`,
    ]
  }

  return [
    `  interface ${name} {`,
    ...members,
    '  }',
  ]
}

export function renderGeneratedBroadcastTypes(
  broadcast: readonly GeneratedBroadcastRegistryEntry[],
  channels: readonly GeneratedChannelRegistryEntry[],
): string {
  const typedBroadcastEntries = broadcast.filter(entry => ['.ts', '.mts', '.cts'].includes(extname(entry.sourcePath)))
  const typedChannelEntries = channels.filter(entry => ['.ts', '.mts', '.cts'].includes(extname(entry.sourcePath)))
  const broadcastImportNameByName = new Map(typedBroadcastEntries.map((entry, index) => [entry.name, `holoBroadcastModule${index}`]))
  const channelImportNameByPattern = new Map(typedChannelEntries.map((entry, index) => [entry.pattern, `holoChannelModule${index}`]))
  const broadcastNeedsDefinitionType = broadcast.some(entry => !broadcastImportNameByName.get(entry.name) || !entry.exportName)
  const broadcastNeedsExportedType = broadcast.some(entry => Boolean(broadcastImportNameByName.get(entry.name) && entry.exportName))
  const channelNeedsDefinitionType = channels.some(entry => !channelImportNameByPattern.get(entry.pattern) || !entry.exportName)
  const channelNeedsExportedType = channels.some(entry => Boolean(channelImportNameByPattern.get(entry.pattern) && entry.exportName))
  const typeImports: string[] = []
  if (broadcastNeedsDefinitionType) typeImports.push('BroadcastDefinition')
  if (channelNeedsDefinitionType) typeImports.push('ChannelDefinition')
  if (broadcastNeedsExportedType) typeImports.push('ExportedBroadcastDefinition')
  if (channelNeedsExportedType) typeImports.push('ExportedChannelDefinition')
  const imports: string[] = []
  if (typeImports.length > 0) {
    imports.push('import type {', ...typeImports.map(typeName => `  ${typeName},`), '} from \'@holo-js/broadcast\'')
  }
  imports.push(
    ...typedBroadcastEntries.map((entry, index) => {
      return `import type * as holoBroadcastModule${index} from '${relativeImportPath(GENERATED_BROADCAST_TYPES_PATH, entry.sourcePath)}'`
    }),
    ...typedChannelEntries.map((entry, index) => {
      return `import type * as holoChannelModule${index} from '${relativeImportPath(GENERATED_BROADCAST_TYPES_PATH, entry.sourcePath)}'`
    }),
  )

  const broadcastMembers = broadcast.map((entry) => {
    const importName = broadcastImportNameByName.get(entry.name)
    if (!importName || !entry.exportName) {
      return `    ${JSON.stringify(entry.name)}: BroadcastDefinition`
    }

    return `    ${JSON.stringify(entry.name)}: ExportedBroadcastDefinition<typeof ${importName}[${JSON.stringify(entry.exportName)}]>`
  })

  const channelMembers = channels.map((entry) => {
    const importName = channelImportNameByPattern.get(entry.pattern)
    if (!importName || !entry.exportName) {
      return `    ${JSON.stringify(entry.pattern)}: ChannelDefinition`
    }

    return `    ${JSON.stringify(entry.pattern)}: ExportedChannelDefinition<typeof ${importName}[${JSON.stringify(entry.exportName)}]>`
  })

  return [
    '// Generated by holo prepare. Do not edit.',
    '',
    ...imports,
    ...(imports.length > 0 ? [''] : []),
    'declare module \'@holo-js/broadcast\' {',
    ...renderAugmentationInterface('HoloBroadcastRegistry', broadcastMembers),
    '',
    ...renderAugmentationInterface('HoloChannelRegistry', channelMembers),
    '}',
    '',
    'export {}',
    '',
  ].join('\n')
}

export function renderGeneratedBroadcastManifest(
  registry: Pick<GeneratedProjectRegistry, 'generatedAt' | 'broadcast' | 'channels'>,
): string {
  const hasPresenceChannels = registry.channels.some(entry => entry.type === 'presence')
  const manifestImports = hasPresenceChannels
    ? [
        'import type { GeneratedBroadcastManifest } from \'@holo-js/core\'',
        'import type { ChannelPresenceMemberFor } from \'@holo-js/broadcast\'',
      ]
    : ['import type { GeneratedBroadcastManifest } from \'@holo-js/core\'']
  const eventLines = registry.broadcast.flatMap((entry, index) => {
    const lines = [
      '    {',
      `      name: ${JSON.stringify(entry.name)},`,
      '      channels: [',
      ...entry.channels.flatMap((channel, channelIndex) => {
        return [
          '        {',
          `          type: ${JSON.stringify(channel.type)},`,
          `          pattern: ${JSON.stringify(channel.pattern)},`,
          `        }${channelIndex < entry.channels.length - 1 ? ',' : ''}`,
        ]
      }),
      '      ],',
      `    }${index < registry.broadcast.length - 1 ? ',' : ''}`,
    ]
    return lines
  })

  const channelLines = registry.channels.flatMap((entry, index) => {
    const lines = [
      '    {',
      `      name: ${JSON.stringify(entry.pattern)},`,
      `      pattern: ${JSON.stringify(entry.pattern)},`,
      `      type: ${JSON.stringify(entry.type)},`,
      `      params: ${JSON.stringify(entry.params)},`,
      `      whispers: ${JSON.stringify(entry.whispers)},`,
    ]

    if (entry.type === 'presence') {
      lines.push(`      member: undefined as unknown as ChannelPresenceMemberFor<${JSON.stringify(entry.pattern)}>,`)
    }

    lines.push(`    }${index < registry.channels.length - 1 ? ',' : ''}`)
    return lines
  })

  return [
    '// Generated by holo prepare. Do not edit.',
    '',
    ...manifestImports,
    '',
    'export const broadcastManifest = {',
    '  version: 1,',
    `  generatedAt: ${JSON.stringify(registry.generatedAt)},`,
    '  events: [',
    ...eventLines,
    '  ],',
    '  channels: [',
    ...channelLines,
    '  ],',
    '} as const satisfies GeneratedBroadcastManifest',
    '',
    'export default broadcastManifest',
    '',
  ].join('\n')
}

export function renderGeneratedEventTypes(
  events: readonly GeneratedEventRegistryEntry[],
  listeners: readonly GeneratedListenerRegistryEntry[],
): string {
  const typedEventEntries = events.filter(entry => ['.ts', '.mts', '.cts'].includes(extname(entry.sourcePath)))
  const typedListenerEntries = listeners.filter(entry => ['.ts', '.mts', '.cts'].includes(extname(entry.sourcePath)))
  const eventImportNameByName = new Map(typedEventEntries.map((entry, index) => [entry.name, `holoEventModule${index}`]))
  const listenerImportNameById = new Map(typedListenerEntries.map((entry, index) => [entry.id, `holoListenerModule${index}`]))
  const needsEventDefinitionType = events.some(entry => !eventImportNameByName.get(entry.name) || !entry.exportName)
  const needsExportedEventType = events.some(entry => Boolean(eventImportNameByName.get(entry.name) && entry.exportName))
  const needsListenerDefinitionType = listeners.some(entry => !listenerImportNameById.get(entry.id) || !entry.exportName)
  const needsTypedListenerDefinitionType = listeners.some(entry => Boolean(listenerImportNameById.get(entry.id) && entry.exportName))
  const typeImports: string[] = []
  if (needsEventDefinitionType) typeImports.push('EventDefinition')
  if (needsExportedEventType) typeImports.push('ExportedEventDefinition')
  if (needsListenerDefinitionType || needsTypedListenerDefinitionType) typeImports.push('ListenerDefinition')
  const imports: string[] = []
  if (typeImports.length > 0) {
    imports.push('import type {', ...typeImports.map(typeName => `  ${typeName},`), '} from \'@holo-js/events\'')
  }
  imports.push(
    ...typedEventEntries.map((entry, index) => {
      return `import type * as holoEventModule${index} from '${relativeImportPath(GENERATED_EVENT_TYPES_PATH, entry.sourcePath)}'`
    }),
    ...typedListenerEntries.map((entry, index) => {
      return `import type * as holoListenerModule${index} from '${relativeImportPath(GENERATED_EVENT_TYPES_PATH, entry.sourcePath)}'`
    }),
  )

  const eventMembers = events.map((entry) => {
    const importName = eventImportNameByName.get(entry.name)
    if (!importName || !entry.exportName) {
      return `    ${JSON.stringify(entry.name)}: EventDefinition`
    }

    return `    ${JSON.stringify(entry.name)}: ExportedEventDefinition<typeof ${importName}[${JSON.stringify(entry.exportName)}]>`
  })

  const listenerMembers = listeners.map((entry) => {
    const importName = listenerImportNameById.get(entry.id)
    if (!importName || !entry.exportName) {
      return `    ${JSON.stringify(entry.id)}: ListenerDefinition`
    }

    return `    ${JSON.stringify(entry.id)}: Extract<typeof ${importName}[${JSON.stringify(entry.exportName)}], ListenerDefinition>`
  })

  return [
    '// Generated by holo prepare. Do not edit.',
    '',
    ...imports,
    ...(imports.length > 0 ? [''] : []),
    'declare module \'@holo-js/events\' {',
    ...renderAugmentationInterface('HoloEventRegistry', eventMembers),
    '',
    ...renderAugmentationInterface('HoloListenerRegistry', listenerMembers),
    '}',
    '',
    'export {}',
    '',
  ].join('\n')
}

export function renderGeneratedQueueTypes(
  jobs: readonly GeneratedJobRegistryEntry[],
): string {
  const typedJobs = jobs.filter(entry => ['.ts', '.mts', '.cts'].includes(extname(entry.sourcePath)))
  const typeImportNameByJob = new Map(
    typedJobs.map((entry, index) => {
      return [entry.name, `holoQueueJobModule${index}`]
    }),
  )
  const needsQueueJobDefinitionType = jobs.some(entry => !typeImportNameByJob.get(entry.name) || !entry.exportName)
  const needsExportedQueueJobDefinitionType = jobs.some(entry => Boolean(typeImportNameByJob.get(entry.name) && entry.exportName))
  const imports = typedJobs.map((entry, index) => {
    return `import type * as holoQueueJobModule${index} from '${relativeImportPath(GENERATED_QUEUE_TYPES_PATH, entry.sourcePath)}'`
  })
  const queueTypeImports: string[] = []
  if (needsQueueJobDefinitionType) queueTypeImports.push('QueueJobDefinition')
  if (needsExportedQueueJobDefinitionType) queueTypeImports.push('ExportedQueueJobDefinition')

  const members = jobs.map((entry) => {
    const importName = typeImportNameByJob.get(entry.name)
    if (!importName || !entry.exportName) {
      return `    ${JSON.stringify(entry.name)}: QueueJobDefinition`
    }

    return `    ${JSON.stringify(entry.name)}: ExportedQueueJobDefinition<typeof ${importName}[${JSON.stringify(entry.exportName)}]>`
  })

  return [
    '// Generated by holo prepare. Do not edit.',
    '',
    ...(queueTypeImports.length > 0
      ? ['import type {', ...queueTypeImports.map(typeName => `  ${typeName},`), '} from \'@holo-js/queue\'']
      : []),
    ...(queueTypeImports.length > 0 ? [''] : []),
    ...imports,
    ...(imports.length > 0 ? [''] : []),
    'declare module \'@holo-js/queue\' {',
    ...renderAugmentationInterface('HoloQueueJobRegistry', members),
    '}',
    '',
    'export {}',
    '',
  ].join('\n')
}

export function renderGeneratedAuthorizationRegistry(
  registry: Pick<GeneratedProjectRegistry, 'generatedAt' | 'authorizationPolicies' | 'authorizationAbilities'>,
): string {
  return [
    '// Generated by holo prepare. Do not edit.',
    '',
    'export const authorization = {',
    `  generatedAt: ${JSON.stringify(registry.generatedAt)},`,
    '  policies: [',
    ...registry.authorizationPolicies.flatMap((entry, index) => {
      return [
        '    {',
        `      sourcePath: ${JSON.stringify(entry.sourcePath)},`,
        `      name: ${JSON.stringify(entry.name)},`,
        ...(entry.exportName ? [`      exportName: ${JSON.stringify(entry.exportName)},`] : []),
        `      target: ${JSON.stringify(entry.target)},`,
        `      classActions: ${JSON.stringify(entry.classActions)},`,
        `      recordActions: ${JSON.stringify(entry.recordActions)},`,
        `    }${index < registry.authorizationPolicies.length - 1 ? ',' : ''}`,
      ]
    }),
    '  ],',
    '  abilities: [',
    ...registry.authorizationAbilities.flatMap((entry, index) => {
      return [
        '    {',
        `      sourcePath: ${JSON.stringify(entry.sourcePath)},`,
        `      name: ${JSON.stringify(entry.name)},`,
        ...(entry.exportName ? [`      exportName: ${JSON.stringify(entry.exportName)},`] : []),
        `    }${index < registry.authorizationAbilities.length - 1 ? ',' : ''}`,
      ]
    }),
    '  ],',
    '} as const',
    '',
    'export default authorization',
    '',
  ].join('\n')
}

export function renderGeneratedAuthorizationTypes(
  authorizationPolicies: readonly GeneratedAuthorizationPolicyRegistryEntry[],
  authorizationAbilities: readonly GeneratedAuthorizationAbilityRegistryEntry[],
  guardNames: readonly string[],
): string {
  const typedPolicyEntries = authorizationPolicies.filter(entry => ['.ts', '.mts', '.cts'].includes(extname(entry.sourcePath)))
  const typedAbilityEntries = authorizationAbilities.filter(entry => ['.ts', '.mts', '.cts'].includes(extname(entry.sourcePath)))
  const policyImportNameByName = new Map(typedPolicyEntries.map((entry, index) => [entry.name, `holoAuthorizationPolicyModule${index}`]))
  const abilityImportNameByName = new Map(typedAbilityEntries.map((entry, index) => [entry.name, `holoAuthorizationAbilityModule${index}`]))

  const imports = [
    ...typedPolicyEntries.map((entry, index) => {
      return `import type * as holoAuthorizationPolicyModule${index} from '${relativeImportPath(GENERATED_AUTHORIZATION_TYPES_PATH, entry.sourcePath)}'`
    }),
    ...typedAbilityEntries.map((entry, index) => {
      return `import type * as holoAuthorizationAbilityModule${index} from '${relativeImportPath(GENERATED_AUTHORIZATION_TYPES_PATH, entry.sourcePath)}'`
    }),
  ]

  const policyMembers = authorizationPolicies.map((entry) => {
    const importName = policyImportNameByName.get(entry.name)
    const classActionEntries = entry.classActions.length > 0
      ? entry.classActions.map(action => `      ${JSON.stringify(action)}: true`)
      : []
    const recordActionEntries = entry.recordActions.length > 0
      ? entry.recordActions.map(action => `      ${JSON.stringify(action)}: true`)
      : []

    if (!importName || !entry.exportName) {
      return [
        `    ${JSON.stringify(entry.name)}: {`,
        '      actor: object',
        `      target: object`,
        '      classActions: {',
        ...classActionEntries,
        '      }',
        '      recordActions: {',
        ...recordActionEntries,
        '      }',
        '    }',
      ].join('\n')
    }

    return [
      `    ${JSON.stringify(entry.name)}: {`,
      '      actor: object',
      `      target: typeof ${importName}[${JSON.stringify(entry.exportName)}] extends import('@holo-js/authorization/contracts').AuthorizationPolicyDefinition<infer _TName, infer TTarget, infer _TClassActions, infer _TRecordActions, infer _TActor> ? TTarget : object`,
      `      classActions: typeof ${importName}[${JSON.stringify(entry.exportName)}] extends import('@holo-js/authorization/contracts').AuthorizationPolicyDefinition<infer _TName, infer _TTarget, infer TClassActions, infer _TRecordActions, infer _TActor> ? {`,
      ...classActionEntries,
      '      } : {',
      ...classActionEntries,
      '      }',
      `      recordActions: typeof ${importName}[${JSON.stringify(entry.exportName)}] extends import('@holo-js/authorization/contracts').AuthorizationPolicyDefinition<infer _TName, infer _TTarget, infer _TClassActions, infer TRecordActions, infer _TActor> ? {`,
      ...recordActionEntries,
      '      } : {',
      ...recordActionEntries,
      '      }',
      '    }',
    ].join('\n')
  })

  const abilityMembers = authorizationAbilities.map((entry) => {
    const importName = abilityImportNameByName.get(entry.name)

    if (!importName || !entry.exportName) {
      return `    ${JSON.stringify(entry.name)}: { actor: object, input: object }`
    }

    return [
      `    ${JSON.stringify(entry.name)}: {`,
      '      actor: object',
      `      input: typeof ${importName}[${JSON.stringify(entry.exportName)}] extends import('@holo-js/authorization/contracts').AuthorizationAbilityDefinition<infer _TName, infer TInput, infer _TActor> ? TInput : object`,
      '    }',
    ].join('\n')
  })

  const guardMembers = guardNames.map((name) => {
    return [
      `    ${JSON.stringify(name)}: {`,
      `      user: import('@holo-js/auth').AuthUser`,
      '    }',
    ].join('\n')
  })

  return [
    '// Generated by holo prepare. Do not edit.',
    '',
    ...(imports.length > 0 ? [...imports, ''] : []),
    'declare module \'@holo-js/authorization/contracts\' {',
    ...renderAugmentationInterface('AuthorizationPolicyRegistry', policyMembers),
    '',
    ...renderAugmentationInterface('AuthorizationAbilityRegistry', abilityMembers),
    '',
    ...renderAugmentationInterface('AuthorizationGuardRegistry', guardMembers),
    '}',
    '',
    'export {}',
    '',
  ].join('\n')
}

export function renderGeneratedTsconfig(): string {
  return renderGeneratedTsconfigForBase('../../tsconfig.json')
}

export async function renderFrameworkAwareTsconfig(projectRoot: string): Promise<string> {
  const base = await resolveGeneratedTsconfigBase(projectRoot)
  return renderGeneratedTsconfigForBase(base)
}

function renderGeneratedTsconfigForBase(basePath: string): string {
  return `${JSON.stringify({
    extends: basePath,
    include: ['./**/*.ts', './**/*.d.ts'],
  }, null, 2)}\n`
}

async function resolveGeneratedTsconfigBase(_projectRoot: string): Promise<string> {
  return '../../tsconfig.json'
}

export function getConfigExtensionPriority(fileName: string): number {
  const extension = extname(fileName)
  const index = CONFIG_EXTENSION_PRIORITY.indexOf(extension as (typeof CONFIG_EXTENSION_PRIORITY)[number])
  return index >= 0 ? index : Number.MAX_SAFE_INTEGER
}

async function collectProjectConfigEntries(projectRoot: string): Promise<Array<{ configName: string, filePath: string }>> {
  const configDir = resolve(projectRoot, 'config')
  const entries = await readdir(configDir, { withFileTypes: true }).catch(() => [])
  const selectedByName = new Map<string, { filePath: string, priority: number }>()

  for (const entry of entries) {
    if (!entry.isFile()) {
      continue
    }

    const extension = extname(entry.name)
    if (!SUPPORTED_CONFIG_EXTENSIONS.has(extension)) {
      continue
    }

    const configName = entry.name.slice(0, entry.name.length - extension.length)
    const filePath = join(configDir, entry.name)
    const priority = getConfigExtensionPriority(entry.name)
    const current = selectedByName.get(configName)

    if (!current || priority < current.priority) {
      selectedByName.set(configName, { filePath, priority })
    }
  }

  return [...selectedByName.entries()]
    .sort((left, right) => left[0].localeCompare(right[0]))
    .map(([configName, entry]) => ({
      configName,
      filePath: entry.filePath,
    }))
}

function renderGeneratedConfigTypes(
  projectRoot: string,
  entries: readonly { configName: string, filePath: string }[],
): string {
  const customEntries = entries.filter(entry => !['app', 'database', 'redis', 'cache', 'storage', 'queue', 'broadcast', 'notifications', 'mail', 'media', 'session', 'security', 'auth'].includes(entry.configName))

  if (customEntries.length === 0) {
    return [
      '// Generated by holo prepare. Do not edit.',
      '',
      'declare module \'@holo-js/config\' {',
      ...renderAugmentationInterface('HoloConfigRegistry', []),
      '}',
      '',
      'export {}',
      '',
    ].join('\n')
  }

  const imports = customEntries.map((entry, index) => {
    return `import type holoConfig${index} from '${relativeImportPath(GENERATED_CONFIG_TYPES_PATH, makeProjectRelativePath(projectRoot, entry.filePath))}'`
  })

  const members = customEntries.map((entry, index) => {
    return `    ${JSON.stringify(entry.configName)}: typeof holoConfig${index}`
  })

  return [
    '// Generated by holo prepare. Do not edit.',
    '',
    ...imports,
    '',
    'declare module \'@holo-js/config\' {',
    ...renderAugmentationInterface('HoloConfigRegistry', members),
    '}',
    '',
    'export {}',
    '',
  ].join('\n')
}

async function writeFileIfChanged(path: string, contents: string): Promise<void> {
  try {
    if (await readFile(path, 'utf8') === contents) {
      return
    }
  } catch {
    // File does not exist yet or cannot be read. Fall through and write it.
  }

  await mkdir(dirname(path), { recursive: true })
  await writeFile(path, contents, 'utf8')
}

function stripGeneratedAt(registry: GeneratedProjectRegistry): Omit<GeneratedProjectRegistry, 'generatedAt'> {
  const { generatedAt: _generatedAt, ...stableRegistry } = registry
  return stableRegistry
}

export async function ensureGeneratedRegistryOwnership(projectRoot: string): Promise<void> {
  await mkdir(resolve(projectRoot, GENERATED_ROOT), { recursive: true })
  await writeFileIfChanged(resolve(projectRoot, GENERATED_GITIGNORE_PATH), '*\n!.gitignore\n')
}

export async function writeGeneratedProjectRegistry(
  projectRoot: string,
  registry: GeneratedProjectRegistry,
): Promise<void> {
  await ensureGeneratedRegistryOwnership(projectRoot)

  const tsconfigPath = resolve(projectRoot, GENERATED_TSCONFIG_PATH)

  await writeFileIfChanged(
    tsconfigPath,
    renderGeneratedTsconfigForBase(await resolveGeneratedTsconfigBase(projectRoot)),
  )
  const loadedConfig = await loadConfigDirectory(projectRoot)
  const configEntries = await collectProjectConfigEntries(projectRoot)
  const existingRegistry = await loadGeneratedProjectRegistry(projectRoot)
  const nextRegistry = existingRegistry && JSON.stringify(stripGeneratedAt(existingRegistry)) === JSON.stringify(stripGeneratedAt(registry))
    ? {
        ...registry,
        generatedAt: existingRegistry.generatedAt,
      }
    : registry

  await writeFileIfChanged(resolve(projectRoot, GENERATED_METADATA_PATH), renderGeneratedModule('metadata', {
    version: nextRegistry.version,
    generatedAt: nextRegistry.generatedAt,
    paths: nextRegistry.paths,
  }))
  await writeFileIfChanged(resolve(projectRoot, GENERATED_MODELS_PATH), renderGeneratedModule('models', nextRegistry.models))
  await writeFileIfChanged(resolve(projectRoot, GENERATED_MIGRATIONS_PATH), renderGeneratedModule('migrations', nextRegistry.migrations))
  await writeFileIfChanged(resolve(projectRoot, GENERATED_SEEDERS_PATH), renderGeneratedModule('seeders', nextRegistry.seeders))
  await writeFileIfChanged(resolve(projectRoot, GENERATED_COMMANDS_PATH), renderGeneratedModule('commands', nextRegistry.commands))
  await writeFileIfChanged(resolve(projectRoot, GENERATED_JOBS_PATH), renderGeneratedModule('jobs', nextRegistry.jobs))
  await writeFileIfChanged(resolve(projectRoot, GENERATED_EVENTS_PATH), renderGeneratedModule('events', nextRegistry.events))
  await writeFileIfChanged(resolve(projectRoot, GENERATED_LISTENERS_PATH), renderGeneratedModule('listeners', nextRegistry.listeners))
  await writeFileIfChanged(resolve(projectRoot, GENERATED_BROADCAST_PATH), renderGeneratedModule('broadcast', nextRegistry.broadcast))
  await writeFileIfChanged(resolve(projectRoot, GENERATED_CHANNELS_PATH), renderGeneratedModule('channels', nextRegistry.channels))
  await writeFileIfChanged(resolve(projectRoot, GENERATED_BROADCAST_MANIFEST_PATH), renderGeneratedBroadcastManifest(nextRegistry))
  await writeFileIfChanged(resolve(projectRoot, GENERATED_BROADCAST_TYPES_PATH), renderGeneratedBroadcastTypes(nextRegistry.broadcast, nextRegistry.channels))
  await writeFileIfChanged(resolve(projectRoot, GENERATED_CONFIG_TYPES_PATH), renderGeneratedConfigTypes(projectRoot, configEntries))
  await writeFileIfChanged(resolve(projectRoot, GENERATED_EVENT_TYPES_PATH), renderGeneratedEventTypes(nextRegistry.events, nextRegistry.listeners))
  await writeFileIfChanged(resolve(projectRoot, GENERATED_QUEUE_TYPES_PATH), renderGeneratedQueueTypes(nextRegistry.jobs))
  await writeFileIfChanged(resolve(projectRoot, GENERATED_AUTHORIZATION_REGISTRY_PATH), renderGeneratedAuthorizationRegistry(nextRegistry))
  await writeFileIfChanged(resolve(projectRoot, GENERATED_AUTHORIZATION_TYPES_PATH), renderGeneratedAuthorizationTypes(
    nextRegistry.authorizationPolicies,
    nextRegistry.authorizationAbilities,
    Object.keys(loadedConfig?.auth?.guards ?? {}).sort((left, right) => left.localeCompare(right)),
  ))
  await syncManagedFrameworkArtifacts(projectRoot)
  await writeFileIfChanged(resolve(projectRoot, GENERATED_INDEX_PATH), renderGeneratedIndexModule())
  await writeFileIfChanged(resolve(projectRoot, GENERATED_REGISTRY_JSON_PATH), `${JSON.stringify(nextRegistry, null, 2)}\n`)
}

export function isGeneratedProjectRegistry(value: unknown): value is GeneratedProjectRegistry {
  if (isRecord(value) && isRecord(value.paths)) {
    value.paths.events ??= DEFAULT_HOLO_PROJECT_PATHS.events
    value.paths.listeners ??= DEFAULT_HOLO_PROJECT_PATHS.listeners
    value.paths.broadcast ??= 'server/broadcast'
    value.paths.channels ??= 'server/channels'
    value.paths.authorizationPolicies ??= 'server/policies'
    value.paths.authorizationAbilities ??= 'server/abilities'
  }

  if (isRecord(value)) {
    value.events ??= []
    value.listeners ??= []
    value.broadcast ??= []
    value.channels ??= []
    value.authorizationPolicies ??= []
    value.authorizationAbilities ??= []
  }

  return isRecord(value)
    && value.version === 1
    && isRecord(value.paths)
    && Array.isArray(value.models)
    && Array.isArray(value.migrations)
    && Array.isArray(value.seeders)
    && Array.isArray(value.commands)
    && Array.isArray(value.jobs)
    && Array.isArray(value.events)
    && Array.isArray(value.listeners)
    && Array.isArray(value.broadcast)
    && Array.isArray(value.channels)
    && Array.isArray(value.authorizationPolicies)
    && Array.isArray(value.authorizationAbilities)
}

export async function loadGeneratedProjectRegistry(
  projectRoot: string,
): Promise<GeneratedProjectRegistry | undefined> {
  const filePath = resolve(projectRoot, GENERATED_INDEX_PATH)
  if (!(await pathExists(filePath))) {
    return undefined
  }

  const moduleValue = await importProjectModule(projectRoot, filePath)
  if (isRecord(moduleValue) && isGeneratedProjectRegistry(moduleValue.default)) {
    return moduleValue.default
  }

  if (isRecord(moduleValue) && isGeneratedProjectRegistry(moduleValue.registry)) {
    return moduleValue.registry
  }

  return undefined
}
