import { mkdir, readFile, readdir, writeFile } from 'node:fs/promises'
import { dirname, extname, join, resolve } from 'node:path'
import { DEFAULT_HOLO_PROJECT_PATHS } from '@holo-js/db'
import { relativeImportPath } from '../templates'
import { importProjectModule } from './runtime'
import {
  CONFIG_EXTENSION_PRIORITY,
  GENERATED_COMMANDS_PATH,
  GENERATED_CONFIG_TYPES_PATH,
  GENERATED_EVENT_TYPES_PATH,
  GENERATED_EVENTS_PATH,
  GENERATED_GITIGNORE_PATH,
  GENERATED_INDEX_PATH,
  GENERATED_JOBS_PATH,
  GENERATED_LISTENERS_PATH,
  GENERATED_METADATA_PATH,
  GENERATED_MIGRATIONS_PATH,
  GENERATED_MODELS_PATH,
  GENERATED_QUEUE_TYPES_PATH,
  GENERATED_REGISTRY_JSON_PATH,
  GENERATED_ROOT,
  GENERATED_SEEDERS_PATH,
  GENERATED_TSCONFIG_PATH,
  SUPPORTED_CONFIG_EXTENSIONS,
  type GeneratedEventRegistryEntry,
  type GeneratedJobRegistryEntry,
  type GeneratedListenerRegistryEntry,
  type GeneratedProjectRegistry,
  isRecord,
  makeProjectRelativePath,
  pathExists,
} from './shared'

export function renderGeneratedModule(exportName: string, value: unknown): string {
  return [
    '// Generated by holo prepare. Do not edit.',
    '',
    `export const ${exportName} = ${JSON.stringify(value, null, 2)}`,
    '',
    `export default ${exportName}`,
    '',
  ].join('\n')
}

export function renderGeneratedIndexModule(): string {
  return [
    '// Generated by holo prepare. Do not edit.',
    '',
    '/// <reference path="./config.d.ts" />',
    '/// <reference path="./events.d.ts" />',
    '/// <reference path="./queue.d.ts" />',
    '',
    'import metadata from \'./metadata\'',
    'import models from \'./models\'',
    'import migrations from \'./migrations\'',
    'import seeders from \'./seeders\'',
    'import commands from \'./commands\'',
    'import jobs from \'./jobs\'',
    'import events from \'./events\'',
    'import listeners from \'./listeners\'',
    '',
    'export { metadata, models, migrations, seeders, commands, jobs, events, listeners }',
    '',
    'export const registry = {',
    '  ...metadata,',
    '  models,',
    '  migrations,',
    '  seeders,',
    '  commands,',
    '  jobs,',
    '  events,',
    '  listeners,',
    '}',
    '',
    'export default registry',
    '',
  ].join('\n')
}

export function renderGeneratedEventTypes(
  events: readonly GeneratedEventRegistryEntry[],
  listeners: readonly GeneratedListenerRegistryEntry[],
): string {
  const typedEventEntries = events.filter(entry => ['.ts', '.mts', '.cts'].includes(extname(entry.sourcePath)))
  const typedListenerEntries = listeners.filter(entry => ['.ts', '.mts', '.cts'].includes(extname(entry.sourcePath)))
  const eventImportNameByName = new Map(typedEventEntries.map((entry, index) => [entry.name, `holoEventModule${index}`]))
  const listenerImportNameById = new Map(typedListenerEntries.map((entry, index) => [entry.id, `holoListenerModule${index}`]))
  const imports = [
    ...typedEventEntries.map((entry, index) => {
      return `import type * as holoEventModule${index} from '${relativeImportPath(GENERATED_EVENT_TYPES_PATH, entry.sourcePath)}'`
    }),
    ...typedListenerEntries.map((entry, index) => {
      return `import type * as holoListenerModule${index} from '${relativeImportPath(GENERATED_EVENT_TYPES_PATH, entry.sourcePath)}'`
    }),
  ]

  const eventMembers = events.map((entry) => {
    const importName = eventImportNameByName.get(entry.name)
    if (!importName || !entry.exportName) {
      return `    ${JSON.stringify(entry.name)}: import('@holo-js/events').EventDefinition`
    }

    return `    ${JSON.stringify(entry.name)}: import('@holo-js/events').ExportedEventDefinition<typeof ${importName}[${JSON.stringify(entry.exportName)}]>`
  })

  const listenerMembers = listeners.map((entry) => {
    const importName = listenerImportNameById.get(entry.id)
    if (!importName || !entry.exportName) {
      return `    ${JSON.stringify(entry.id)}: import('@holo-js/events').ListenerDefinition`
    }

    return `    ${JSON.stringify(entry.id)}: Extract<typeof ${importName}[${JSON.stringify(entry.exportName)}], import('@holo-js/events').ListenerDefinition>`
  })

  return [
    '// Generated by holo prepare. Do not edit.',
    '',
    ...imports,
    ...(imports.length > 0 ? [''] : []),
    'declare module \'@holo-js/events\' {',
    '  interface HoloEventRegistry {',
    ...eventMembers,
    '  }',
    '',
    '  interface HoloListenerRegistry {',
    ...listenerMembers,
    '  }',
    '}',
    '',
    'export {}',
    '',
  ].join('\n')
}

export function renderGeneratedQueueTypes(
  jobs: readonly GeneratedJobRegistryEntry[],
): string {
  const typedJobs = jobs.filter(entry => ['.ts', '.mts', '.cts'].includes(extname(entry.sourcePath)))
  const typeImportNameByJob = new Map(
    typedJobs.map((entry, index) => {
      return [entry.name, `holoQueueJobModule${index}`]
    }),
  )
  const imports = typedJobs.map((entry, index) => {
    return `import type * as holoQueueJobModule${index} from '${relativeImportPath(GENERATED_QUEUE_TYPES_PATH, entry.sourcePath)}'`
  })

  const members = jobs.map((entry) => {
    const importName = typeImportNameByJob.get(entry.name)
    if (!importName || !entry.exportName) {
      return `    ${JSON.stringify(entry.name)}: import('@holo-js/queue').QueueJobDefinition`
    }

    return `    ${JSON.stringify(entry.name)}: import('@holo-js/queue').ExportedQueueJobDefinition<typeof ${importName}[${JSON.stringify(entry.exportName)}]>`
  })

  return [
    '// Generated by holo prepare. Do not edit.',
    '',
    ...imports,
    ...(imports.length > 0 ? [''] : []),
    'declare module \'@holo-js/queue\' {',
    '  interface HoloQueueJobRegistry {',
    ...members,
    '  }',
    '}',
    '',
    'export {}',
    '',
  ].join('\n')
}

export function renderGeneratedTsconfig(): string {
  return `${JSON.stringify({
    extends: '../../tsconfig.json',
    include: ['./**/*.ts', './**/*.d.ts'],
  }, null, 2)}\n`
}

export function getConfigExtensionPriority(fileName: string): number {
  const extension = extname(fileName)
  const index = CONFIG_EXTENSION_PRIORITY.indexOf(extension as (typeof CONFIG_EXTENSION_PRIORITY)[number])
  return index >= 0 ? index : Number.MAX_SAFE_INTEGER
}

async function collectProjectConfigEntries(projectRoot: string): Promise<Array<{ configName: string, filePath: string }>> {
  const configDir = resolve(projectRoot, 'config')
  const entries = await readdir(configDir, { withFileTypes: true }).catch(() => [])
  const selectedByName = new Map<string, { filePath: string, priority: number }>()

  for (const entry of entries) {
    if (!entry.isFile()) {
      continue
    }

    const extension = extname(entry.name)
    if (!SUPPORTED_CONFIG_EXTENSIONS.has(extension)) {
      continue
    }

    const configName = entry.name.slice(0, entry.name.length - extension.length)
    const filePath = join(configDir, entry.name)
    const priority = getConfigExtensionPriority(entry.name)
    const current = selectedByName.get(configName)

    if (!current || priority < current.priority) {
      selectedByName.set(configName, { filePath, priority })
    }
  }

  return [...selectedByName.entries()]
    .sort((left, right) => left[0].localeCompare(right[0]))
    .map(([configName, entry]) => ({
      configName,
      filePath: entry.filePath,
    }))
}

function renderGeneratedConfigTypes(
  projectRoot: string,
  entries: readonly { configName: string, filePath: string }[],
): string {
  const customEntries = entries.filter(entry => !['app', 'database', 'storage', 'queue', 'notifications', 'mail', 'media'].includes(entry.configName))

  if (customEntries.length === 0) {
    return [
      '// Generated by holo prepare. Do not edit.',
      '',
      'declare module \'@holo-js/config\' {',
      '  interface HoloConfigRegistry {}',
      '}',
      '',
      'export {}',
      '',
    ].join('\n')
  }

  const imports = customEntries.map((entry, index) => {
    return `import type holoConfig${index} from '${relativeImportPath(GENERATED_CONFIG_TYPES_PATH, makeProjectRelativePath(projectRoot, entry.filePath))}'`
  })

  const members = customEntries.map((entry, index) => {
    return `    ${JSON.stringify(entry.configName)}: typeof holoConfig${index}`
  })

  return [
    '// Generated by holo prepare. Do not edit.',
    '',
    ...imports,
    '',
    'declare module \'@holo-js/config\' {',
    '  interface HoloConfigRegistry {',
    ...members,
    '  }',
    '}',
    '',
    'export {}',
    '',
  ].join('\n')
}

async function writeFileIfChanged(path: string, contents: string): Promise<void> {
  try {
    if (await readFile(path, 'utf8') === contents) {
      return
    }
  } catch {
    // File does not exist yet or cannot be read. Fall through and write it.
  }

  await mkdir(dirname(path), { recursive: true })
  await writeFile(path, contents, 'utf8')
}

function stripGeneratedAt(registry: GeneratedProjectRegistry): Omit<GeneratedProjectRegistry, 'generatedAt'> {
  const { generatedAt: _generatedAt, ...stableRegistry } = registry
  return stableRegistry
}

export async function ensureGeneratedRegistryOwnership(projectRoot: string): Promise<void> {
  await mkdir(resolve(projectRoot, GENERATED_ROOT), { recursive: true })
  await writeFileIfChanged(resolve(projectRoot, GENERATED_GITIGNORE_PATH), '*\n!.gitignore\n')
  await writeFileIfChanged(resolve(projectRoot, GENERATED_TSCONFIG_PATH), renderGeneratedTsconfig())
}

export async function writeGeneratedProjectRegistry(
  projectRoot: string,
  registry: GeneratedProjectRegistry,
): Promise<void> {
  await ensureGeneratedRegistryOwnership(projectRoot)
  const configEntries = await collectProjectConfigEntries(projectRoot)
  const existingRegistry = await loadGeneratedProjectRegistry(projectRoot)
  const nextRegistry = existingRegistry && JSON.stringify(stripGeneratedAt(existingRegistry)) === JSON.stringify(stripGeneratedAt(registry))
    ? {
        ...registry,
        generatedAt: existingRegistry.generatedAt,
      }
    : registry

  await writeFileIfChanged(resolve(projectRoot, GENERATED_METADATA_PATH), renderGeneratedModule('metadata', {
    version: nextRegistry.version,
    generatedAt: nextRegistry.generatedAt,
    paths: nextRegistry.paths,
  }))
  await writeFileIfChanged(resolve(projectRoot, GENERATED_MODELS_PATH), renderGeneratedModule('models', nextRegistry.models))
  await writeFileIfChanged(resolve(projectRoot, GENERATED_MIGRATIONS_PATH), renderGeneratedModule('migrations', nextRegistry.migrations))
  await writeFileIfChanged(resolve(projectRoot, GENERATED_SEEDERS_PATH), renderGeneratedModule('seeders', nextRegistry.seeders))
  await writeFileIfChanged(resolve(projectRoot, GENERATED_COMMANDS_PATH), renderGeneratedModule('commands', nextRegistry.commands))
  await writeFileIfChanged(resolve(projectRoot, GENERATED_JOBS_PATH), renderGeneratedModule('jobs', nextRegistry.jobs))
  await writeFileIfChanged(resolve(projectRoot, GENERATED_EVENTS_PATH), renderGeneratedModule('events', nextRegistry.events))
  await writeFileIfChanged(resolve(projectRoot, GENERATED_LISTENERS_PATH), renderGeneratedModule('listeners', nextRegistry.listeners))
  await writeFileIfChanged(resolve(projectRoot, GENERATED_CONFIG_TYPES_PATH), renderGeneratedConfigTypes(projectRoot, configEntries))
  await writeFileIfChanged(resolve(projectRoot, GENERATED_EVENT_TYPES_PATH), renderGeneratedEventTypes(nextRegistry.events, nextRegistry.listeners))
  await writeFileIfChanged(resolve(projectRoot, GENERATED_QUEUE_TYPES_PATH), renderGeneratedQueueTypes(nextRegistry.jobs))
  await writeFileIfChanged(resolve(projectRoot, GENERATED_INDEX_PATH), renderGeneratedIndexModule())
  await writeFileIfChanged(resolve(projectRoot, GENERATED_REGISTRY_JSON_PATH), `${JSON.stringify(nextRegistry, null, 2)}\n`)
}

export function isGeneratedProjectRegistry(value: unknown): value is GeneratedProjectRegistry {
  if (isRecord(value) && isRecord(value.paths)) {
    value.paths.events ??= DEFAULT_HOLO_PROJECT_PATHS.events
    value.paths.listeners ??= DEFAULT_HOLO_PROJECT_PATHS.listeners
  }

  if (isRecord(value)) {
    value.events ??= []
    value.listeners ??= []
  }

  return isRecord(value)
    && value.version === 1
    && isRecord(value.paths)
    && Array.isArray(value.models)
    && Array.isArray(value.migrations)
    && Array.isArray(value.seeders)
    && Array.isArray(value.commands)
    && Array.isArray(value.jobs)
    && Array.isArray(value.events)
    && Array.isArray(value.listeners)
}

export async function loadGeneratedProjectRegistry(
  projectRoot: string,
): Promise<GeneratedProjectRegistry | undefined> {
  const filePath = resolve(projectRoot, GENERATED_INDEX_PATH)
  if (!(await pathExists(filePath))) {
    return undefined
  }

  const moduleValue = await importProjectModule(projectRoot, filePath)
  if (isRecord(moduleValue) && isGeneratedProjectRegistry(moduleValue.default)) {
    return moduleValue.default
  }

  if (isRecord(moduleValue) && isGeneratedProjectRegistry(moduleValue.registry)) {
    return moduleValue.registry
  }

  return undefined
}
