import { mkdir, readdir, readFile, rm, writeFile } from 'node:fs/promises'
import { dirname, extname, relative, resolve, sep } from 'node:path'
import {
  GENERATED_SVELTE_HOOKS_PATH,
  GENERATED_SVELTE_SERVER_HOOKS_PATH,
} from './shared'
import {
  renderNextManagedHostedAuthRouteFiles,
  renderNextGeneratedRealtimeDefinitions,
  renderNextManagedRouteFiles,
  renderNextHoloHelper,
  renderSvelteHoloHelper,
  renderSvelteManagedRuntimeFiles,
} from './scaffold/framework-renderers'

type SvelteManagedFeatures = {
  readonly authEnabled: boolean
  readonly broadcastEnabled: boolean
  readonly storageEnabled: boolean
  readonly clerkEnabled: boolean
  readonly workosEnabled: boolean
}

function renderManagedSvelteHooksModule(): string {
  return [
    '// Generated by holo prepare. Do not edit.',
    '',
    'import type { Reroute } from \'@sveltejs/kit\'',
    'import { holoSvelteKitTransport } from \'@holo-js/adapter-sveltekit/transport\'',
    'import * as userHooks from \'../../src/hooks\'',
    '',
    'const universalHooks = userHooks as {',
    '  reroute?: Reroute',
    '  transport?: Partial<typeof holoSvelteKitTransport>',
    '}',
    '',
    'function normalizeStorageRoutePrefix(value: string | undefined): string {',
    '  const raw = value?.trim() ?? \'/storage\'',
    '  if (!raw || raw === \'/\') {',
    '    return \'/storage\'',
    '  }',
    '',
    '  return `/${raw.replace(/^\\/+|\\/+$/g, \'\')}`',
    '}',
    '',
    'function resolveStorageRoutePrefix(): string {',
    '  return normalizeStorageRoutePrefix(typeof process === \'undefined\' ? undefined : process.env.STORAGE_ROUTE_PREFIX)',
    '}',
    '',
    'export const reroute: Reroute = async (event) => {',
    '  const userPath = await universalHooks.reroute?.(event)',
    '  const pathname = typeof userPath === \'string\' ? userPath : event.url.pathname',
    '  const storageRoutePrefix = resolveStorageRoutePrefix()',
    '',
    '  if (storageRoutePrefix !== \'/storage\' && (pathname === storageRoutePrefix || pathname.startsWith(`${storageRoutePrefix}/`))) {',
    '    const suffix = pathname.slice(storageRoutePrefix.length)',
    '    return suffix ? `/storage${suffix}` : \'/storage\'',
    '  }',
    '',
    '  return userPath',
    '}',
    'export const transport = {',
    '  ...(universalHooks.transport ?? {}),',
    '  ...holoSvelteKitTransport,',
    '}',
    '',
  ].join('\n')
}

function renderManagedSvelteServerHooksModule(features: SvelteManagedFeatures): string {
  const imports = [
    '// Generated by holo prepare. Do not edit.',
    '',
    'import { error as svelteKitError, type Handle, type HandleFetch, type HandleServerError, type RequestEvent } from \'@sveltejs/kit\'',
    'import { adapterSvelteKitInternals, runWithSvelteKitRequestEvent } from \'@holo-js/adapter-sveltekit\'',
    'import { sequence } from \'@sveltejs/kit/hooks\'',
    ...(features.authEnabled
      ? ['import auth, { check, isAuthError, provider, user } from \'@holo-js/auth\'']
      : []),
    ...(features.broadcastEnabled
      ? [
          'import { renderBroadcastAuthResponse } from \'@holo-js/broadcast/auth\'',
          'import { renderBroadcastClientConfigResponse } from \'@holo-js/broadcast/client-config\'',
        ]
      : []),
    ...(features.storageEnabled
      ? ['import { createPublicStorageResponse } from \'@holo-js/storage\'']
      : []),
    ...(features.clerkEnabled
      ? ['import { completeClerkAuth, loginWithClerk, logoutWithClerk, registerWithClerk } from \'@holo-js/auth-clerk\'']
      : []),
    ...(features.workosEnabled
      ? ['import { completeWorkosAuth, loginWithWorkos, logoutWithWorkos, registerWithWorkos } from \'@holo-js/auth-workos\'']
      : []),
    'import { holo } from \'./sveltekit/holo\'',
    'import * as userHooks from \'../../src/hooks.server\'',
    '',
  ]
  const routeHandlers = [
    ...(features.authEnabled ? ['handleHoloCurrentAuthRoute'] : []),
    ...(features.storageEnabled ? ['handleHoloStorageRoute'] : []),
    ...(features.broadcastEnabled ? ['handleHoloBroadcastConfigRoute', 'handleHoloBroadcastAuthRoute'] : []),
    ...(features.clerkEnabled
      ? [
          'handleHoloClerkLoginRoute',
          'handleHoloClerkRegisterRoute',
          'handleHoloClerkCallbackRoute',
          'handleHoloClerkLogoutRoute',
        ]
      : []),
    ...(features.workosEnabled
      ? [
          'handleHoloWorkosLoginRoute',
          'handleHoloWorkosRegisterRoute',
          'handleHoloWorkosCallbackRoute',
          'handleHoloWorkosLogoutRoute',
        ]
      : []),
  ]

  return [
    ...imports,
    'const serverHooks = userHooks as {',
    '  handle?: Handle',
    '  handleError?: HandleServerError',
    '  handleFetch?: HandleFetch',
    '}',
    '',
    'type HoloApp = Awaited<ReturnType<typeof holo.getApp>>',
    'type HoloRouteHandler = (event: RequestEvent, app: HoloApp) => Promise<Response | undefined>',
    '',
    'function isRoute(event: RequestEvent, method: string, paths: readonly string[]): boolean {',
    '  return event.request.method.toUpperCase() === method && paths.includes(event.url.pathname)',
    '}',
    '',
    'function redirectResponse(event: RequestEvent, location: string): Response {',
    '  return Response.redirect(new URL(location, event.url), 303)',
    '}',
    '',
    'function normalizeRoutePrefix(value: string | undefined, fallback: string): string {',
    '  const raw = value?.trim() ?? fallback',
    '  if (!raw || raw === \'/\') {',
    '    return fallback',
    '  }',
    '',
    '  return `/${raw.replace(/^\\/+|\\/+$/g, \'\')}`',
    '}',
    '',
    'function pathMatchesPrefix(pathname: string, prefix: string): boolean {',
    '  return pathname === prefix || pathname.startsWith(`${prefix}/`)',
    '}',
    '',
    ...(features.authEnabled
      ? [
          'async function handleHoloCurrentAuthRoute(event: RequestEvent): Promise<Response | undefined> {',
          '  if (!isRoute(event, \'GET\', [\'/api/auth/user\'])) {',
          '    return undefined',
          '  }',
          '',
          '  const guard = event.url.searchParams.get(\'guard\') ?? undefined',
          '  try {',
          '    const guardAuth = guard ? auth.guard(guard) : undefined',
          '',
          '    return Response.json({',
          '      authenticated: guardAuth ? await guardAuth.check() : await check(),',
          '      guard: guard ?? \'web\',',
          '      provider: guardAuth ? await guardAuth.provider() : await provider(),',
          '      user: guardAuth ? await guardAuth.user() : await user(),',
          '    })',
          '  } catch (error) {',
          '    if (isAuthError(error) && error.code === \'guard_not_configured\') {',
          '      return Response.json({',
          '        authenticated: false,',
          '        guard: guard ?? \'web\',',
          '        provider: null,',
          '        user: null,',
          '      }, { status: 400 })',
          '    }',
          '',
          '    throw error',
          '  }',
          '}',
          '',
        ]
      : []),
    ...(features.storageEnabled
      ? [
          'async function handleHoloStorageRoute(event: RequestEvent, app: HoloApp): Promise<Response | undefined> {',
          '  if (event.request.method.toUpperCase() !== \'GET\') {',
          '    return undefined',
          '  }',
          '',
          '  const prefix = normalizeRoutePrefix(app.config.storage.routePrefix, \'/storage\')',
          '  if (!pathMatchesPrefix(event.url.pathname, prefix)) {',
          '    return undefined',
          '  }',
          '',
          '  return createPublicStorageResponse(app.projectRoot, app.config.storage, event.request)',
          '}',
          '',
        ]
      : []),
    ...(features.broadcastEnabled
      ? [
          'async function handleHoloBroadcastConfigRoute(event: RequestEvent, app: HoloApp): Promise<Response | undefined> {',
          '  if (!isRoute(event, \'GET\', [\'/broadcasting/config\'])) {',
          '    return undefined',
          '  }',
          '',
          '  return renderBroadcastClientConfigResponse(app.config.broadcast)',
          '}',
          '',
          'async function handleHoloBroadcastAuthRoute(event: RequestEvent, app: HoloApp): Promise<Response | undefined> {',
          '  if (!isRoute(event, \'POST\', [\'/broadcasting/auth\'])) {',
          '    return undefined',
          '  }',
          '',
          '  const auth = await holo.getAuth()',
          '  return await renderBroadcastAuthResponse(event.request, {',
          '    resolveUser: async (_request, context) => {',
          '      const guardAuth = context.guard ? auth?.guard(context.guard) : undefined',
          '      return guardAuth ? await guardAuth.user() : await auth?.user()',
          '    },',
          '    channelAuth: {',
          '      registry: {',
          '        projectRoot: app.projectRoot,',
          '        channels: app.registry?.channels ?? [],',
          '      },',
          '    },',
          '  })',
          '}',
          '',
        ]
      : []),
    ...(features.clerkEnabled
      ? renderSvelteHostedAuthHookRoutes('clerk', 'Clerk')
      : []),
    ...(features.workosEnabled
      ? renderSvelteHostedAuthHookRoutes('workos', 'Workos')
      : []),
    `const holoRouteHandlers: readonly HoloRouteHandler[] = [${routeHandlers.join(', ')}]`,
    '',
    'async function handleHoloRoute(event: RequestEvent, app: HoloApp): Promise<Response | undefined> {',
    '  for (const handler of holoRouteHandlers) {',
    '    const response = await handler(event, app)',
    '    if (response) {',
    '      return response',
    '    }',
    '  }',
    '',
    '  return undefined',
    '}',
    '',
    'function isHoloAuthorizationHttpError(cause: unknown): cause is Error & { readonly decision: { readonly status: 403 | 404 } } {',
    '  if (!(cause instanceof Error) || cause.name !== \'AuthorizationError\') {',
    '    return false',
    '  }',
    '',
    '  const decision = (cause as { readonly decision?: { readonly status?: unknown } }).decision',
    '  return decision?.status === 403 || decision?.status === 404',
    '}',
    '',
    'function serializeHoloValidationException(cause: unknown) {',
    '  return adapterSvelteKitInternals.serializeValidationException(cause) ?? null',
    '}',
    '',
    'const holoHandle: Handle = ({ event, resolve }) => runWithSvelteKitRequestEvent(event, async () => {',
    '  const app = await holo.getApp()',
    '',
    '  try {',
    '    const holoRouteResponse = await handleHoloRoute(event, app)',
    '    if (holoRouteResponse) {',
    '      return holoRouteResponse',
    '    }',
    '',
    '    const response = await resolve(event)',
    '    return await adapterSvelteKitInternals.mapValidationActionResponse(event, response)',
    '  } catch (cause) {',
    '    if (isHoloAuthorizationHttpError(cause)) {',
    '      svelteKitError(cause.decision.status, cause.message)',
    '    }',
    '',
    '    const validationPayload = serializeHoloValidationException(cause)',
    '    if (validationPayload) {',
    '      if (adapterSvelteKitInternals.isApiEvent(event)) {',
    '        return Response.json(validationPayload, { status: validationPayload.status })',
    '      }',
    '',
    '      throw cause',
    '    }',
    '',
    '    throw cause',
    '  }',
    '})',
    '',
    'const holoHandleError: HandleServerError = async (input) => {',
    '  const validationPayload = serializeHoloValidationException(input.error)',
    '  if (validationPayload) {',
    '    adapterSvelteKitInternals.rememberValidationActionFailure(input.event, validationPayload)',
    '    return validationPayload',
    '  }',
    '',
    '  if (serverHooks.handleError) {',
    '    return await serverHooks.handleError(input)',
    '  }',
    '',
    '  return {',
    '    message: input.error instanceof Error ? input.error.message : \'Internal server error\',',
    '  }',
    '}',
    '',
    'export const handle = typeof serverHooks.handle === \'function\'',
    '  ? sequence(holoHandle, serverHooks.handle)',
    '  : holoHandle',
    'export const handleError = holoHandleError',
    'export const handleFetch = serverHooks.handleFetch',
    '',
  ].join('\n')
}

function renderSvelteHostedAuthHookRoutes(providerName: 'clerk' | 'workos', functionSuffix: 'Clerk' | 'Workos'): readonly string[] {
  return [
    `async function handleHolo${functionSuffix}LoginRoute(event: RequestEvent): Promise<Response | undefined> {`,
    `  if (!isRoute(event, 'GET', ['/api/auth/${providerName}/login'])) {`,
    '    return undefined',
    '  }',
    '',
    `  return await loginWith${functionSuffix}(event)`,
    '}',
    '',
    `async function handleHolo${functionSuffix}RegisterRoute(event: RequestEvent): Promise<Response | undefined> {`,
    `  if (!isRoute(event, 'GET', ['/api/auth/${providerName}/register'])) {`,
    '    return undefined',
    '  }',
    '',
    `  return await registerWith${functionSuffix}(event)`,
    '}',
    '',
    `async function handleHolo${functionSuffix}CallbackRoute(event: RequestEvent): Promise<Response | undefined> {`,
    `  if (!isRoute(event, 'GET', ['/api/auth/${providerName}/callback'])) {`,
    '    return undefined',
    '  }',
    '',
    `  const { error } = await complete${functionSuffix}Auth(event)`,
    '  if (error) {',
    '    return redirectResponse(event, `/login?error=${encodeURIComponent(error.code)}`)',
    '  }',
    '',
    '  return redirectResponse(event, \'/\')',
    '}',
    '',
    `async function handleHolo${functionSuffix}LogoutRoute(event: RequestEvent): Promise<Response | undefined> {`,
    `  if (!isRoute(event, 'POST', ['/api/auth/${providerName}/logout'])) {`,
    '    return undefined',
    '  }',
    '',
    '  let currentProvider: string | null',
    '  try {',
    '    currentProvider = await provider()',
    '  } catch {',
    '    return redirectResponse(event, \'/\')',
    '  }',
    '',
    `  if (currentProvider !== '${providerName}') {`,
    '    return redirectResponse(event, \'/\')',
    '  }',
    '',
    `  const { data, error } = await logoutWith${functionSuffix}(event)`,
    '  if (error) {',
    '    return Response.json({ data, error }, { status: error.status })',
    '  }',
    '',
    '  return redirectResponse(event, data.url)',
    '}',
    '',
  ]
}

function renderSvelteDefaultHooksModule(): string {
  return [
    'export {}',
    '',
  ].join('\n')
}

function renderSvelteDefaultServerHooksModule(): string {
  return [
    'export {}',
    '',
  ].join('\n')
}

function isManagedPrepareArtifact(contents: string): boolean {
  return contents.startsWith('// Generated by holo prepare. Do not edit.')
}

function isLegacySvelteTransportHook(contents: string): boolean {
  return contents.trim() === [
    'import { holoSvelteKitTransport } from \'@holo-js/adapter-sveltekit/transport\'',
    '',
    'export const transport = holoSvelteKitTransport',
  ].join('\n').trim()
}

function isLegacySvelteServerHook(contents: string): boolean {
  return contents.trim() === [
    'import \'@holo-js/adapter-sveltekit\'',
    '',
    'import type { Handle } from \'@sveltejs/kit\'',
    'import { holo } from \'$lib/server/holo\'',
    '',
    'function normalizeStorageRoutePrefix(value: string | undefined): string {',
    '  const raw = value?.trim() ?? \'/storage\'',
    '  if (!raw || raw === \'/\') {',
    '    return \'/storage\'',
    '  }',
    '',
    '  return `/${raw.replace(/^\\/+|\\/+$/g, \'\')}`',
    '}',
    '',
    'export const handle: Handle = async ({ event, resolve }) => {',
    '  await holo.getApp()',
    '',
    '  const storageRoutePrefix = normalizeStorageRoutePrefix(process.env.STORAGE_ROUTE_PREFIX)',
    '',
    '  if (storageRoutePrefix !== \'/storage\') {',
    '    const pathname = event.url.pathname',
    '    if (pathname === storageRoutePrefix || pathname.startsWith(`${storageRoutePrefix}/`)) {',
    '      const suffix = pathname.slice(storageRoutePrefix.length)',
    '      event.url.pathname = suffix ? `/storage${suffix}` : \'/storage\'',
    '    }',
    '  }',
    '',
    '  return resolve(event)',
    '}',
  ].join('\n').trim()
}

async function readFileIfPresent(path: string): Promise<string | undefined> {
  try {
    return await readFile(path, 'utf8')
  } catch {
    return undefined
  }
}

async function unlinkIfPresent(path: string): Promise<void> {
  await rm(path, { force: true })
}

async function pathExists(path: string): Promise<boolean> {
  return (await readFileIfPresent(path)) !== undefined
}

const SVELTE_HOOKS_OVERRIDE_BLOCK = [
  '    files: {',
  '      hooks: {',
  '        server: \'.holo-js/generated/hooks.server\',',
  '        universal: \'.holo-js/generated/hooks\',',
  '      },',
  '    },',
].join('\n')
const SVELTE_CONFIG_WRAPPER_IMPORT = 'import { withHoloSvelteKit } from \'@holo-js/adapter-sveltekit/config\''
const LEGACY_SVELTE_PREPROCESS_IMPORT = 'import { holoSveltePreprocess } from \'@holo-js/adapter-sveltekit\''
const LEGACY_SVELTE_PREPROCESS_CALL = 'holoSveltePreprocess()'
const SVELTE_CONFIG_WRAPPER_CALL = 'withHoloSvelteKit('

function getSvelteConfigHooksOverrideState(contents: string): 'managed' | 'custom' | 'none' {
  if (contents.includes('.holo-js/generated/hooks')) {
    return 'managed'
  }

  if (/kit\s*:\s*\{[\s\S]*?files\s*:\s*\{[\s\S]*?hooks\s*:/.test(contents)) {
    return 'custom'
  }

  return 'none'
}

function assertSvelteConfigHasNoCustomHookOverride(contents: string): void {
  const hooksOverrideState = getSvelteConfigHooksOverrideState(contents)
  if (hooksOverrideState === 'custom') {
    throw new Error('Custom SvelteKit hook entrypoints are not supported. Remove kit.files.hooks from svelte.config.js and let holo prepare manage the generated hook bridge.')
  }
}

function ensureSvelteConfigWrapperImport(contents: string): string {
  if (contents.includes(SVELTE_CONFIG_WRAPPER_IMPORT)) {
    return contents
  }

  const lastImport = [...contents.matchAll(/^import .+$/gm)].at(-1)
  if (!lastImport || lastImport.index === undefined) {
    return `${SVELTE_CONFIG_WRAPPER_IMPORT}\n${contents}`
  }

  const insertAt = lastImport.index + lastImport[0].length
  return `${contents.slice(0, insertAt)}\n${SVELTE_CONFIG_WRAPPER_IMPORT}${contents.slice(insertAt)}`
}

function removeLegacySvelteConfigWiring(contents: string): string {
  return contents
    .replace(`${LEGACY_SVELTE_PREPROCESS_IMPORT}\n`, '')
    .replace(new RegExp(String.raw`,\s*${LEGACY_SVELTE_PREPROCESS_CALL.replace(/[.*+?^${}()|[\]\\]/g, '\\$&')}`, 'g'), '')
    .replace(new RegExp(String.raw`${LEGACY_SVELTE_PREPROCESS_CALL.replace(/[.*+?^${}()|[\]\\]/g, '\\$&')}\s*,\s*`, 'g'), '')
    .replace(`${SVELTE_HOOKS_OVERRIDE_BLOCK}\n`, '')
}

function patchSvelteConfigWithHoloWrapper(contents: string): string | undefined {
  assertSvelteConfigHasNoCustomHookOverride(contents)

  const cleaned = ensureSvelteConfigWrapperImport(removeLegacySvelteConfigWiring(contents))
  if (cleaned.includes(SVELTE_CONFIG_WRAPPER_CALL)) {
    return cleaned === contents ? undefined : cleaned
  }

  const constConfigPattern = /(const\s+config\s*=\s*)\{/
  if (!constConfigPattern.test(cleaned)) {
    throw new Error('Could not patch svelte.config.js with withHoloSvelteKit(). Export a const config object so holo prepare can manage the SvelteKit integration.')
  }

  const wrappedOpening = cleaned.replace(constConfigPattern, `$1${SVELTE_CONFIG_WRAPPER_CALL}{`)
  const wrapped = wrappedOpening.replace(/\}\s*export\s+default\s+config\s*$/u, '})\n\nexport default config')
  if (wrapped === wrappedOpening) {
    throw new Error('Could not patch svelte.config.js with withHoloSvelteKit(). Export a const config object so holo prepare can manage the SvelteKit integration.')
  }

  return wrapped
}

async function ensureSvelteConfigHooksOverride(projectRoot: string): Promise<void> {
  const configPath = resolve(projectRoot, 'svelte.config.js')
  const contents = await readFileIfPresent(configPath)
  if (!contents) {
    return
  }

  const patched = patchSvelteConfigWithHoloWrapper(contents) ?? contents
  if (patched !== contents) {
    await writeFile(configPath, patched, 'utf8')
  }
}

async function writeFileIfChanged(path: string, contents: string): Promise<void> {
  if ((await readFileIfPresent(path)) === contents) {
    return
  }

  await mkdir(dirname(path), { recursive: true })
  await writeFile(path, contents, 'utf8')
}

async function ensureSvelteManagedHooks(projectRoot: string, features: SvelteManagedFeatures): Promise<void> {
  const hooksPath = resolve(projectRoot, 'src/hooks.ts')
  const hooksServerPath = resolve(projectRoot, 'src/hooks.server.ts')
  const generatedHooksPath = resolve(projectRoot, GENERATED_SVELTE_HOOKS_PATH)
  const generatedServerHooksPath = resolve(projectRoot, GENERATED_SVELTE_SERVER_HOOKS_PATH)
  const legacyHooksUserPath = resolve(projectRoot, 'src/hooks.user.ts')
  const legacyHooksServerUserPath = resolve(projectRoot, 'src/hooks.server.user.ts')
  const [hooksContents, hooksServerContents, legacyUserContents, legacyServerUserContents] = await Promise.all([
    readFileIfPresent(hooksPath),
    readFileIfPresent(hooksServerPath),
    readFileIfPresent(legacyHooksUserPath),
    readFileIfPresent(legacyHooksServerUserPath),
  ])

  if (legacyUserContents && (!hooksContents || isManagedPrepareArtifact(hooksContents))) {
    await writeFileIfChanged(hooksPath, legacyUserContents)
    await unlinkIfPresent(legacyHooksUserPath)
  } else if (legacyUserContents && hooksContents === legacyUserContents) {
    await unlinkIfPresent(legacyHooksUserPath)
  }

  if (legacyServerUserContents && (!hooksServerContents || isManagedPrepareArtifact(hooksServerContents))) {
    await writeFileIfChanged(hooksServerPath, legacyServerUserContents)
    await unlinkIfPresent(legacyHooksServerUserPath)
  } else if (legacyServerUserContents && hooksServerContents === legacyServerUserContents) {
    await unlinkIfPresent(legacyHooksServerUserPath)
  }

  const currentHooks = await readFileIfPresent(hooksPath)
  if (!currentHooks || isManagedPrepareArtifact(currentHooks) || isLegacySvelteTransportHook(currentHooks)) {
    await writeFileIfChanged(hooksPath, renderSvelteDefaultHooksModule())
  }

  const currentServerHooks = await readFileIfPresent(hooksServerPath)
  if (!currentServerHooks || isManagedPrepareArtifact(currentServerHooks) || isLegacySvelteServerHook(currentServerHooks)) {
    await writeFileIfChanged(hooksServerPath, renderSvelteDefaultServerHooksModule())
  }

  await writeFileIfChanged(generatedHooksPath, renderManagedSvelteHooksModule())
  await writeFileIfChanged(generatedServerHooksPath, renderManagedSvelteServerHooksModule(features))
  await ensureSvelteConfigHooksOverride(projectRoot)
}

async function removeLegacyManagedHoloHelper(path: string, managedContents: string): Promise<void> {
  const contents = await readFileIfPresent(path)
  const trimmedContents = contents?.trim()
  const trimmedManagedContents = managedContents.trim()
  const isLegacyManagedHelper = trimmedContents === [
    'import { createNextHoloHelpers } from \'@holo-js/adapter-next\'',
    '',
    'export const holo = createNextHoloHelpers()',
  ].join('\n') || trimmedContents === [
    'import { createSvelteKitHoloHelpers } from \'@holo-js/adapter-sveltekit\'',
    '',
    'export const holo = createSvelteKitHoloHelpers()',
  ].join('\n')

  if (trimmedContents === trimmedManagedContents || isLegacyManagedHelper) {
    await unlinkIfPresent(path)
  }
}

async function removeLegacyManagedRoute(
  path: string,
  markerGroups: readonly (readonly string[])[],
): Promise<void> {
  const contents = await readFileIfPresent(path)
  if (contents && markerGroups.some(markers => markers.every(marker => contents.includes(marker)))) {
    await unlinkIfPresent(path)
  }
}

async function directoryContainsText(path: string, pattern: string): Promise<boolean> {
  const entries = await readdir(path, { withFileTypes: true }).catch(() => [])
  for (const entry of entries) {
    const entryPath = resolve(path, entry.name)
    if (entry.isDirectory()) {
      if (await directoryContainsText(entryPath, pattern)) {
        return true
      }
      continue
    }

    if (!entry.isFile() || !/\.[cm]?[jt]s$/.test(entry.name)) {
      continue
    }

    const contents = await readFileIfPresent(entryPath)
    if (contents?.includes(pattern)) {
      return true
    }
  }

  return false
}

const realtimeDefinitionExtensions = new Set(['.ts', '.mts', '.cts', '.js', '.mjs', '.cjs'])

async function collectRealtimeDefinitionFiles(root: string): Promise<readonly string[]> {
  const entries = await readdir(root, { withFileTypes: true }).catch(() => [])
  const files = await Promise.all(entries.map(async (entry) => {
    const entryPath = resolve(root, entry.name)
    if (entry.isDirectory()) {
      return await collectRealtimeDefinitionFiles(entryPath)
    }

    return realtimeDefinitionExtensions.has(extname(entry.name)) ? [entryPath] : []
  }))

  return files.flat().sort((left, right) => left.localeCompare(right))
}

async function renderNextRealtimeDefinitions(projectRoot: string): Promise<string> {
  const generatedRoot = resolve(projectRoot, '.holo-js/generated/next')
  const files = await collectRealtimeDefinitionFiles(resolve(projectRoot, 'server/realtime'))
  const importPaths = files.map((filePath) => {
    const withoutExtension = filePath.slice(0, -extname(filePath).length)
    const importPath = relative(generatedRoot, withoutExtension).split(sep).join('/')
    return importPath.startsWith('.') ? importPath : `./${importPath}`
  })

  return renderNextGeneratedRealtimeDefinitions(importPaths)
}

async function ensureNextManagedRoutes(projectRoot: string): Promise<void> {
  const authEnabled = await pathExists(resolve(projectRoot, 'app/api/auth/user/route.ts'))
  const storageEnabled = await pathExists(resolve(projectRoot, 'app/storage/[[...path]]/route.ts'))
  const broadcastEnabled = await pathExists(resolve(projectRoot, 'app/broadcasting/config/route.ts'))
  const broadcastAuthEnabled = await pathExists(resolve(projectRoot, 'app/broadcasting/auth/route.ts'))
  const realtimeEnabled = await pathExists(resolve(projectRoot, 'server/realtime'))
  const clerkEnabled = await pathExists(resolve(projectRoot, 'app/api/auth/clerk/login/route.ts'))
  const workosEnabled = await pathExists(resolve(projectRoot, 'app/api/auth/workos/login/route.ts'))
  const files = [
    ...renderNextManagedRouteFiles({
      authEnabled,
      broadcastEnabled,
      storageEnabled,
      broadcastAuthEnabled,
      realtimeEnabled,
    }),
    ...renderNextManagedHostedAuthRouteFiles({
      clerk: clerkEnabled,
      workos: workosEnabled,
    }),
  ]

  for (const file of files) {
    await writeFileIfChanged(resolve(projectRoot, file.path), file.contents)
  }

  if (realtimeEnabled) {
    await writeFileIfChanged(
      resolve(projectRoot, '.holo-js/generated/next/realtime-definitions.ts'),
      await renderNextRealtimeDefinitions(projectRoot),
    )
  }

  await removeLegacyManagedHoloHelper(resolve(projectRoot, 'server/holo.ts'), renderNextHoloHelper())
}

function isRecord(value: unknown): value is Record<string, unknown> {
  return !!value && typeof value === 'object' && !Array.isArray(value)
}

async function readProjectDependencies(projectRoot: string): Promise<ReadonlySet<string>> {
  const contents = await readFileIfPresent(resolve(projectRoot, 'package.json'))
  if (!contents) {
    return new Set()
  }

  const manifest = JSON.parse(contents) as unknown
  if (!isRecord(manifest)) {
    return new Set()
  }

  const dependencies = isRecord(manifest.dependencies) ? Object.keys(manifest.dependencies) : []
  const devDependencies = isRecord(manifest.devDependencies) ? Object.keys(manifest.devDependencies) : []
  return new Set([...dependencies, ...devDependencies])
}

async function resolveSvelteManagedFeatures(projectRoot: string): Promise<SvelteManagedFeatures> {
  const dependencies = await readProjectDependencies(projectRoot)

  return {
    authEnabled: dependencies.has('@holo-js/auth'),
    broadcastEnabled: dependencies.has('@holo-js/broadcast'),
    storageEnabled: dependencies.has('@holo-js/storage'),
    clerkEnabled: dependencies.has('@holo-js/auth-clerk'),
    workosEnabled: dependencies.has('@holo-js/auth-workos'),
  }
}

async function ensureSvelteManagedRuntime(projectRoot: string): Promise<void> {
  const files = renderSvelteManagedRuntimeFiles()

  for (const file of files) {
    await writeFileIfChanged(resolve(projectRoot, file.path), file.contents)
  }

}

async function ensureSvelteManagedRoutes(projectRoot: string): Promise<void> {
  await removeLegacyManagedRoute(
    resolve(projectRoot, 'src/routes/api/holo/health/+server.ts'),
    [
      ['app.registry?.models.length ?? 0', 'app.registry?.commands.length ?? 0'],
      ['.holo-js/generated/sveltekit/health-route'],
    ],
  )
  await removeLegacyManagedRoute(
    resolve(projectRoot, 'src/routes/api/holo/+server.ts'),
    [
      ['app.registry?.models.length ?? 0', 'app.registry?.commands.length ?? 0'],
      ['.holo-js/generated/sveltekit/health-route'],
    ],
  )
  await removeLegacyManagedRoute(
    resolve(projectRoot, 'src/routes/api/auth/user/+server.ts'),
    [
      ['authenticated:', 'guard:', 'provider:', 'user:'],
      ['.holo-js/generated/sveltekit/auth-user-route'],
    ],
  )
  await removeLegacyManagedRoute(
    resolve(projectRoot, 'src/routes/storage/[...path]/+server.ts'),
    [
      ['createPublicStorageResponse', 'app.config.storage'],
      ['.holo-js/generated/sveltekit/storage-route'],
    ],
  )
  await removeLegacyManagedRoute(
    resolve(projectRoot, 'src/routes/broadcasting/auth/+server.ts'),
    [
      ['renderBroadcastAuthResponse', 'channelAuth'],
      ['.holo-js/generated/sveltekit/broadcast-auth-route'],
    ],
  )
  if (!(await directoryContainsText(resolve(projectRoot, 'src'), '$lib/server/holo'))) {
    await removeLegacyManagedHoloHelper(resolve(projectRoot, 'src/lib/server/holo.ts'), renderSvelteHoloHelper())
  }
}

export async function syncManagedFrameworkArtifacts(projectRoot: string): Promise<void> {
  let manifest: { framework?: string }
  try {
    const content = await readFile(resolve(projectRoot, '.holo-js/framework/project.json'), 'utf8')
    manifest = JSON.parse(content) as { framework?: string }
  } catch {
    return
  }

  if (manifest.framework === 'sveltekit') {
    const features = await resolveSvelteManagedFeatures(projectRoot)
    await ensureSvelteManagedRuntime(projectRoot)
    await ensureSvelteManagedHooks(projectRoot, features)
    await ensureSvelteManagedRoutes(projectRoot)
  }

  if (manifest.framework === 'next') {
    await ensureNextManagedRoutes(projectRoot)
  }
}
