import { readFile, unlink, writeFile } from 'node:fs/promises'
import { resolve } from 'node:path'
import {
  GENERATED_SVELTE_HOOKS_PATH,
  GENERATED_SVELTE_SERVER_HOOKS_PATH,
} from './shared'

function renderManagedSvelteHooksModule(): string {
  return [
    '// Generated by holo prepare. Do not edit.',
    '',
    'import type { Reroute } from \'@sveltejs/kit\'',
    'import { holoSvelteKitTransport } from \'@holo-js/adapter-sveltekit/transport\'',
    'import * as userHooks from \'../../src/hooks\'',
    '',
    'const universalHooks = userHooks as {',
    '  reroute?: Reroute',
    '  transport?: Partial<typeof holoSvelteKitTransport>',
    '}',
    '',
    'export const reroute = universalHooks.reroute',
    'export const transport = {',
    '  ...(universalHooks.transport ?? {}),',
    '  ...holoSvelteKitTransport,',
    '}',
    '',
  ].join('\n')
}

function renderManagedSvelteServerHooksModule(): string {
  return [
    '// Generated by holo prepare. Do not edit.',
    '',
    'import \'@holo-js/adapter-sveltekit\'',
    '',
    'import type { Handle, HandleFetch, HandleServerError } from \'@sveltejs/kit\'',
    'import { sequence } from \'@sveltejs/kit/hooks\'',
    'import { holo } from \'$lib/server/holo\'',
    'import * as userHooks from \'../../src/hooks.server\'',
    '',
    'const serverHooks = userHooks as {',
    '  handle?: Handle',
    '  handleError?: HandleServerError',
    '  handleFetch?: HandleFetch',
    '}',
    '',
    'function normalizeStorageRoutePrefix(value: string | undefined): string {',
    '  const raw = value?.trim() ?? \'/storage\'',
    '  if (!raw || raw === \'/\') {',
    '    return \'/storage\'',
    '  }',
    '',
    '  return `/${raw.replace(/^\\/+|\\/+$/g, \'\')}`',
    '}',
    '',
    'const holoHandle: Handle = async ({ event, resolve }) => {',
    '  await holo.getApp()',
    '',
    '  const storageRoutePrefix = normalizeStorageRoutePrefix(process.env.STORAGE_ROUTE_PREFIX)',
    '',
    '  if (storageRoutePrefix !== \'/storage\') {',
    '    const pathname = event.url.pathname',
    '    if (pathname === storageRoutePrefix || pathname.startsWith(`${storageRoutePrefix}/`)) {',
    '      const suffix = pathname.slice(storageRoutePrefix.length)',
    '      event.url.pathname = suffix ? `/storage${suffix}` : \'/storage\'',
    '    }',
    '  }',
    '',
    '  return resolve(event)',
    '}',
    '',
    'export const handle = typeof serverHooks.handle === \'function\'',
    '  ? sequence(holoHandle, serverHooks.handle)',
    '  : holoHandle',
    'export const handleError = serverHooks.handleError',
    'export const handleFetch = serverHooks.handleFetch',
    '',
  ].join('\n')
}

function renderSvelteDefaultHooksModule(): string {
  return [
    'export {}',
    '',
  ].join('\n')
}

function renderSvelteDefaultServerHooksModule(): string {
  return [
    'export {}',
    '',
  ].join('\n')
}

function isManagedPrepareArtifact(contents: string): boolean {
  return contents.startsWith('// Generated by holo prepare. Do not edit.')
}

function isLegacySvelteTransportHook(contents: string): boolean {
  return contents.trim() === [
    'import { holoSvelteKitTransport } from \'@holo-js/adapter-sveltekit/transport\'',
    '',
    'export const transport = holoSvelteKitTransport',
  ].join('\n').trim()
}

function isLegacySvelteServerHook(contents: string): boolean {
  return contents.trim() === [
    'import \'@holo-js/adapter-sveltekit\'',
    '',
    'import type { Handle } from \'@sveltejs/kit\'',
    'import { holo } from \'$lib/server/holo\'',
    '',
    'function normalizeStorageRoutePrefix(value: string | undefined): string {',
    '  const raw = value?.trim() ?? \'/storage\'',
    '  if (!raw || raw === \'/\') {',
    '    return \'/storage\'',
    '  }',
    '',
    '  return `/${raw.replace(/^\\/+|\\/+$/g, \'\')}`',
    '}',
    '',
    'export const handle: Handle = async ({ event, resolve }) => {',
    '  await holo.getApp()',
    '',
    '  const storageRoutePrefix = normalizeStorageRoutePrefix(process.env.STORAGE_ROUTE_PREFIX)',
    '',
    '  if (storageRoutePrefix !== \'/storage\') {',
    '    const pathname = event.url.pathname',
    '    if (pathname === storageRoutePrefix || pathname.startsWith(`${storageRoutePrefix}/`)) {',
    '      const suffix = pathname.slice(storageRoutePrefix.length)',
    '      event.url.pathname = suffix ? `/storage${suffix}` : \'/storage\'',
    '    }',
    '  }',
    '',
    '  return resolve(event)',
    '}',
  ].join('\n').trim()
}

async function readFileIfPresent(path: string): Promise<string | undefined> {
  try {
    return await readFile(path, 'utf8')
  } catch {
    return undefined
  }
}

async function unlinkIfPresent(path: string): Promise<void> {
  try {
    await unlink(path)
  } catch {
    // File does not exist or cannot be removed. Ignore.
  }
}

const SVELTE_HOOKS_OVERRIDE_BLOCK = [
  '    files: {',
  '      hooks: {',
  '        server: \'.holo-js/generated/hooks.server\',',
  '        universal: \'.holo-js/generated/hooks\',',
  '      },',
  '    },',
].join('\n')

function getSvelteConfigHooksOverrideState(contents: string): 'managed' | 'custom' | 'none' {
  if (contents.includes('.holo-js/generated/hooks')) {
    return 'managed'
  }

  if (/kit\s*:\s*\{[\s\S]*?files\s*:\s*\{[\s\S]*?hooks\s*:/.test(contents)) {
    return 'custom'
  }

  return 'none'
}

function patchSvelteConfigWithHooksOverride(contents: string): string | undefined {
  const hooksOverrideState = getSvelteConfigHooksOverrideState(contents)
  if (hooksOverrideState === 'managed') return undefined

  if (hooksOverrideState === 'custom') {
    throw new Error('Custom SvelteKit hook entrypoints are not supported. Remove kit.files.hooks from svelte.config.js and let holo prepare manage the generated hook bridge.')
  }

  const singleLineKitPattern = /(kit:\s*\{)([^\n{}]*?)(\s*\},?)/m
  const singleLineKitMatch = contents.match(singleLineKitPattern)
  if (singleLineKitMatch) {
    const opening = singleLineKitMatch[1] ?? 'kit: {'
    const body = singleLineKitMatch[2] ?? ''
    const closing = singleLineKitMatch[3] ?? '}'
    const trimmedBody = body.trim()
    const suffix = closing.trimStart().startsWith('},') ? ',' : ''
    const bodyLines = trimmedBody
      ? trimmedBody
        .split(',')
        .map(segment => segment.trim())
        .filter(Boolean)
        .map(segment => `    ${segment},`)
      : []

    const replacement = [
      opening,
      ...bodyLines,
      SVELTE_HOOKS_OVERRIDE_BLOCK,
      `  }${suffix}`,
    ].join('\n')

    return contents.replace(singleLineKitPattern, replacement)
  }

  const patched = contents.replace(
    /(kit:\s*\{)([^\n]*\n?)/,
    (match, opening: string, rest: string) => `${opening}${rest}${SVELTE_HOOKS_OVERRIDE_BLOCK}\n`,
  )

  return patched !== contents ? patched : undefined
}

async function ensureSvelteConfigHooksOverride(projectRoot: string): Promise<void> {
  const configPath = resolve(projectRoot, 'svelte.config.js')
  const contents = await readFileIfPresent(configPath)
  if (!contents) {
    return
  }

  const patched = patchSvelteConfigWithHooksOverride(contents)
  if (patched) {
    await writeFile(configPath, patched, 'utf8')
  }
}

async function writeFileIfChanged(path: string, contents: string): Promise<void> {
  if ((await readFileIfPresent(path)) === contents) {
    return
  }

  await writeFile(path, contents, 'utf8')
}

async function ensureSvelteManagedHooks(projectRoot: string): Promise<void> {
  const hooksPath = resolve(projectRoot, 'src/hooks.ts')
  const hooksServerPath = resolve(projectRoot, 'src/hooks.server.ts')
  const generatedHooksPath = resolve(projectRoot, GENERATED_SVELTE_HOOKS_PATH)
  const generatedServerHooksPath = resolve(projectRoot, GENERATED_SVELTE_SERVER_HOOKS_PATH)
  const legacyHooksUserPath = resolve(projectRoot, 'src/hooks.user.ts')
  const legacyHooksServerUserPath = resolve(projectRoot, 'src/hooks.server.user.ts')
  const [hooksContents, hooksServerContents, legacyUserContents, legacyServerUserContents] = await Promise.all([
    readFileIfPresent(hooksPath),
    readFileIfPresent(hooksServerPath),
    readFileIfPresent(legacyHooksUserPath),
    readFileIfPresent(legacyHooksServerUserPath),
  ])

  if (legacyUserContents && (!hooksContents || isManagedPrepareArtifact(hooksContents))) {
    await writeFileIfChanged(hooksPath, legacyUserContents)
    await unlinkIfPresent(legacyHooksUserPath)
  } else if (legacyUserContents && hooksContents === legacyUserContents) {
    await unlinkIfPresent(legacyHooksUserPath)
  }

  if (legacyServerUserContents && (!hooksServerContents || isManagedPrepareArtifact(hooksServerContents))) {
    await writeFileIfChanged(hooksServerPath, legacyServerUserContents)
    await unlinkIfPresent(legacyHooksServerUserPath)
  } else if (legacyServerUserContents && hooksServerContents === legacyServerUserContents) {
    await unlinkIfPresent(legacyHooksServerUserPath)
  }

  const currentHooks = await readFileIfPresent(hooksPath)
  if (!currentHooks || isManagedPrepareArtifact(currentHooks) || isLegacySvelteTransportHook(currentHooks)) {
    await writeFileIfChanged(hooksPath, renderSvelteDefaultHooksModule())
  }

  const currentServerHooks = await readFileIfPresent(hooksServerPath)
  if (!currentServerHooks || isManagedPrepareArtifact(currentServerHooks) || isLegacySvelteServerHook(currentServerHooks)) {
    await writeFileIfChanged(hooksServerPath, renderSvelteDefaultServerHooksModule())
  }

  await writeFileIfChanged(generatedHooksPath, renderManagedSvelteHooksModule())
  await writeFileIfChanged(generatedServerHooksPath, renderManagedSvelteServerHooksModule())
  await ensureSvelteConfigHooksOverride(projectRoot)
}

export async function syncManagedFrameworkArtifacts(projectRoot: string): Promise<void> {
  let manifest: { framework?: string }
  try {
    const content = await readFile(resolve(projectRoot, '.holo-js/framework/project.json'), 'utf8')
    manifest = JSON.parse(content) as { framework?: string }
  } catch {
    return
  }

  if (manifest.framework === 'sveltekit') {
    await ensureSvelteManagedHooks(projectRoot)
  }
}
