import {
  normalizeScaffoldOptionalPackages,
  type ProjectScaffoldOptions,
} from '../shared'
import type { ScaffoldedFile } from './types'

function renderNuxtAppVue(projectName: string): string {
  return [
    '<template>',
    '  <main class="shell">',
    '    <h1>{{ appName }}</h1>',
    '    <p>Nuxt renders the UI. Holo owns the backend runtime and canonical server directories.</p>',
    '  </main>',
    '</template>',
    '',
    '<script setup lang="ts">',
    `const appName = ${JSON.stringify(projectName)}`,
    '</script>',
    '',
    '<style scoped>',
    '.shell {',
    '  min-height: 100vh;',
    '  display: grid;',
    '  place-content: center;',
    '  gap: 1rem;',
    '  padding: 3rem;',
    '  font-family: sans-serif;',
    '}',
    'h1 {',
    '  margin: 0;',
    '  font-size: clamp(2.5rem, 6vw, 4rem);',
    '}',
    'p {',
    '  margin: 0;',
    '  max-width: 40rem;',
    '  line-height: 1.6;',
    '}',
    '</style>',
    '',
  ].join('\n')
}

function renderNuxtConfig(): string {
  return [
    'export default defineNuxtConfig({',
    '  modules: [\'@holo-js/adapter-nuxt\'],',
    '  sourcemap: {',
    '    client: false,',
    '    server: false,',
    '  },',
    '  vite: {',
    '    build: {',
    '      rollupOptions: {',
    '        onwarn(warning, defaultHandler) {',
    '          if (',
    '            warning.message.includes(\'nuxt:module-preload-polyfill\')',
    '            && warning.message.includes(\'didn\\\'t generate a sourcemap\')',
    '          ) {',
    '            return',
    '          }',
    '',
    '          defaultHandler(warning)',
    '        },',
    '      },',
    '    },',
    '  },',
    '})',
    '',
  ].join('\n')
}

function renderNuxtHealthRoute(): string {
  return [
    'export default defineEventHandler(async () => {',
    '  const app = await holo.getApp()',
    '',
    '  return {',
    '    ok: true,',
    '    app: app.config.app.name,',
    '    env: app.config.app.env,',
    '    models: app.registry?.models.length ?? 0,',
    '    commands: app.registry?.commands.length ?? 0,',
    '  }',
    '})',
    '',
  ].join('\n')
}

function renderNextConfig(): string {
  return [
    'import type { NextConfig } from \'next\'',
    'import { withHolo } from \'@holo-js/adapter-next/config\'',
    '',
    'const nextConfig: NextConfig = withHolo({',
    '  /* config options here */',
    '})',
    '',
    'export default nextConfig',
    '',
  ].join('\n')
}

function renderNextLayout(projectName: string): string {
  return [
    'import type { ReactNode } from \'react\'',
    '',
    'export const metadata = {',
    `  title: ${JSON.stringify(projectName)},`,
    '  description: \'Holo on Next.js\',',
    '}',
    '',
    'export default function RootLayout({ children }: { children: ReactNode }) {',
    '  return (',
    '    <html lang="en">',
    '      <body>{children}</body>',
    '    </html>',
    '  )',
    '}',
    '',
  ].join('\n')
}

function escapeHtml(value: string): string {
  return value
    .replaceAll('&', '&amp;')
    .replaceAll('<', '&lt;')
    .replaceAll('>', '&gt;')
    .replaceAll('"', '&quot;')
    .replaceAll('\'', '&#39;')
    .replaceAll('{', '&#123;')
    .replaceAll('}', '&#125;')
}

function renderNextPage(projectName: string): string {
  const escapedProjectName = escapeHtml(projectName)

  return [
    'export default function HomePage() {',
    '  return (',
    '    <main style={{ padding: \'3rem\', fontFamily: \'sans-serif\' }}>',
    `      <h1>${escapedProjectName}</h1>`,
    '      <p>Next.js handles rendering. Holo powers the backend runtime and discovered server resources.</p>',
    '    </main>',
    '  )',
    '}',
    '',
  ].join('\n')
}

function renderNextEnvDts(): string {
  return [
    '/// <reference types="next" />',
    '/// <reference types="next/image-types/global" />',
    '',
    '// Generated by Holo. Do not edit.',
    '',
  ].join('\n')
}

export function renderNextHoloHelper(): string {
  return [
    'import { createNextHoloHelpers } from \'@holo-js/adapter-next\'',
    '',
    'export const holo = createNextHoloHelpers()',
    '',
  ].join('\n')
}

function renderNextInstrumentation(): string {
  return [
    'export async function register() {',
    '  if (process.env.NEXT_RUNTIME === \'nodejs\') {',
    '    const { holo } = await import(\'@/server/holo\')',
    '    await holo.getApp()',
    '  }',
    '}',
    '',
  ].join('\n')
}

function renderNextHealthRoute(): string {
  return [
    'import { holo } from \'@/server/holo\'',
    '',
    'export async function GET() {',
    '  const app = await holo.getApp()',
    '',
    '  return Response.json({',
    '    ok: true,',
    '    app: app.config.app.name,',
    '    env: app.config.app.env,',
    '    models: app.registry?.models.length ?? 0,',
    '    commands: app.registry?.commands.length ?? 0,',
    '  })',
    '}',
    '',
  ].join('\n')
}

function renderNextStorageRoute(): string {
  return [
    'import { holo } from \'@/server/holo\'',
    'import { createPublicStorageResponse } from \'@holo-js/storage\'',
    '',
    'export async function GET(request: Request) {',
    '  const app = await holo.getApp()',
    '  return createPublicStorageResponse(app.projectRoot, app.config.storage, request)',
    '}',
    '',
  ].join('\n')
}

function renderSvelteConfig(): string {
  return [
    'import adapter from \'@sveltejs/adapter-node\'',
    'import { vitePreprocess } from \'@sveltejs/vite-plugin-svelte\'',
    '',
    '/** @type {import(\'@sveltejs/kit\').Config} */',
    'const config = {',
    '  preprocess: vitePreprocess(),',
    '  kit: {',
    '    adapter: adapter(),',
    '    files: {',
    '      hooks: {',
    '        server: \'.holo-js/generated/hooks.server\',',
    '        universal: \'.holo-js/generated/hooks\',',
    '      },',
    '    },',
    '  },',
    '}',
    '',
    'export default config',
    '',
  ].join('\n')
}

function renderSvelteUserHooks(): string {
  return [
    'export {}',
    '',
  ].join('\n')
}

function renderSvelteServerUserHooks(): string {
  return [
    'export {}',
    '',
  ].join('\n')
}

function renderSvelteViteConfig(storageEnabled: boolean): string {
  const externals = [
    '      \'@holo-js/adapter-sveltekit\',',
    '      \'@holo-js/config\',',
    '      \'@holo-js/core\',',
    '      \'@holo-js/db\',',
    ...(storageEnabled
      ? [
          '      \'@holo-js/storage\',',
          '      \'@holo-js/storage/runtime\',',
        ]
      : []),
    '      \'better-sqlite3\',',
  ]

  return [
    'import { sveltekit } from \'@sveltejs/kit/vite\'',
    'import { defineConfig } from \'vite\'',
    '',
    'export default defineConfig({',
    '  plugins: [sveltekit()],',
    '  server: {',
    '    fs: {',
    '      allow: [\'.holo-js/generated\'],',
    '    },',
    '  },',
    '  ssr: {',
    '    external: [',
    ...externals,
    '    ],',
    '  },',
    '})',
    '',
  ].join('\n')
}

function renderSvelteAppHtml(): string {
  return [
    '<!doctype html>',
    '<html lang="en">',
    '  <head>',
    '    <meta charset="utf-8" />',
    '    <meta name="viewport" content="width=device-width, initial-scale=1" />',
    '    %sveltekit.head%',
    '  </head>',
    '  <body data-sveltekit-preload-data="hover">',
    '    <div style="display: contents">%sveltekit.body%</div>',
    '  </body>',
    '</html>',
    '',
  ].join('\n')
}

function renderSveltePage(projectName: string): string {
  const escapedProjectName = escapeHtml(projectName)

  return [
    `<svelte:head><title>${escapedProjectName}</title></svelte:head>`,
    '',
    '<script lang="ts">',
    `  const projectName = ${JSON.stringify(projectName)}`,
    '</script>',
    '',
    '<main class="shell">',
    '  <h1>{projectName}</h1>',
    '  <p>SvelteKit owns rendering. Holo owns config, discovery, and backend runtime services.</p>',
    '</main>',
    '',
    '<style>',
    '  .shell {',
    '    min-height: 100vh;',
    '    display: grid;',
    '    place-content: center;',
    '    gap: 1rem;',
    '    padding: 3rem;',
    '    font-family: sans-serif;',
    '  }',
    '  h1 {',
    '    margin: 0;',
    '    font-size: clamp(2.5rem, 6vw, 4rem);',
    '  }',
    '  p {',
    '    margin: 0;',
    '    max-width: 40rem;',
    '    line-height: 1.6;',
    '  }',
    '</style>',
    '',
  ].join('\n')
}

export function renderSvelteHoloHelper(): string {
  return [
    'import { createSvelteKitHoloHelpers } from \'@holo-js/adapter-sveltekit\'',
    '',
    'export const holo = createSvelteKitHoloHelpers()',
    '',
  ].join('\n')
}

function renderSvelteHealthRoute(): string {
  return [
    'import { json } from \'@sveltejs/kit\'',
    'import { holo } from \'$lib/server/holo\'',
    '',
    'export async function GET() {',
    '  const app = await holo.getApp()',
    '',
    '  return json({',
    '    ok: true,',
    '    app: app.config.app.name,',
    '    env: app.config.app.env,',
    '    models: app.registry?.models.length ?? 0,',
    '    commands: app.registry?.commands.length ?? 0,',
    '  })',
    '}',
    '',
  ].join('\n')
}

function renderSvelteStorageRoute(): string {
  return [
    'import { holo } from \'$lib/server/holo\'',
    'import { createPublicStorageResponse } from \'@holo-js/storage\'',
    '',
    'export async function GET({ request }: { request: Request }) {',
    '  const app = await holo.getApp()',
    '  return createPublicStorageResponse(app.projectRoot, app.config.storage, request)',
    '}',
    '',
  ].join('\n')
}

export function renderFrameworkFiles(options: ProjectScaffoldOptions): readonly ScaffoldedFile[] {
  const optionalPackages = normalizeScaffoldOptionalPackages(options.optionalPackages)
  const storageEnabled = optionalPackages.includes('storage')

  if (options.framework === 'nuxt') {
    return [
      { path: 'app.vue', contents: renderNuxtAppVue(options.projectName) },
      { path: 'nuxt.config.ts', contents: renderNuxtConfig() },
      { path: 'server/api/holo/health.get.ts', contents: renderNuxtHealthRoute() },
    ]
  }

  if (options.framework === 'next') {
    return [
      { path: 'next.config.ts', contents: renderNextConfig() },
      { path: 'next-env.d.ts', contents: renderNextEnvDts() },
      { path: 'app/layout.tsx', contents: renderNextLayout(options.projectName) },
      { path: 'app/page.tsx', contents: renderNextPage(options.projectName) },
      { path: 'app/api/holo/health/route.ts', contents: renderNextHealthRoute() },
      ...(storageEnabled
        ? [{ path: 'app/storage/[[...path]]/route.ts', contents: renderNextStorageRoute() }]
        : []),
      { path: 'server/holo.ts', contents: renderNextHoloHelper() },
      { path: 'instrumentation.ts', contents: renderNextInstrumentation() },
    ]
  }

  return [
    { path: 'svelte.config.js', contents: renderSvelteConfig() },
    { path: 'vite.config.ts', contents: renderSvelteViteConfig(storageEnabled) },
    { path: 'src/hooks.ts', contents: renderSvelteUserHooks() },
    { path: 'src/hooks.server.ts', contents: renderSvelteServerUserHooks() },
    { path: 'src/app.html', contents: renderSvelteAppHtml() },
    { path: 'src/routes/+page.svelte', contents: renderSveltePage(options.projectName) },
    { path: 'src/routes/api/holo/health/+server.ts', contents: renderSvelteHealthRoute() },
    ...(storageEnabled
      ? [{ path: 'src/routes/storage/[...path]/+server.ts', contents: renderSvelteStorageRoute() }]
      : []),
    { path: 'src/lib/server/holo.ts', contents: renderSvelteHoloHelper() },
  ]
}

export function renderFrameworkRunner(options: Pick<ProjectScaffoldOptions, 'framework'>): string {
  const commandName = options.framework === 'nuxt'
    ? 'nuxi'
    : options.framework === 'next'
      ? 'next'
      : 'vite'
  return [
    'import { existsSync, readFileSync, readlinkSync } from \'node:fs\'',
    'import { dirname, resolve } from \'node:path\'',
    'import { fileURLToPath, pathToFileURL } from \'node:url\'',
    'import { execFileSync, spawn } from \'node:child_process\'',
    '',
    'const mode = process.argv[2]',
    'const manifestPath = fileURLToPath(new URL(\'./project.json\', import.meta.url))',
    'const projectRoot = resolve(dirname(manifestPath), \'../..\')',
    'const runtimeSchemaPath = resolve(projectRoot, \'.holo-js/generated/schema.mjs\')',
    'const manifest = JSON.parse(readFileSync(manifestPath, \'utf8\'))',
    'const framework = String(manifest.framework ?? \'\')',
    `const commandName = ${JSON.stringify(commandName)}`,
    'const commandArgs = mode === \'dev\'',
    '  ? [\'dev\']',
    '  : mode === \'build\'',
    '    ? framework === \'sveltekit\' ? [\'build\', \'--logLevel\', \'error\'] : [\'build\']',
    '    : undefined',
    '',
    'if (!commandArgs) {',
    '  console.error(`[holo] Unknown framework runner mode: ${String(mode)}`)',
    '  process.exit(1)',
    '}',
    '',
    'const binaryPath = resolve(',
    '  projectRoot,',
    '  \'node_modules\',',
    '  \'.bin\',',
    '  process.platform === \'win32\' ? `${commandName}.cmd` : commandName,',
    ')',
    '',
    'const suppressedOutput = framework === \'sveltekit\'',
    '  ? new Set([',
    '      \'"try_get_request_store" is imported from external module "@sveltejs/kit/internal/server" but never used in ".svelte-kit/adapter-node/index.js".\',',
    '    ])',
    '  : new Set()',
    '',
    'function pipeOutput(stream, target, onLine) {',
    '  if (!stream) {',
    '    return',
    '  }',
    '',
    '  let buffered = \'\'',
    '  stream.on(\'data\', (chunk) => {',
    '    buffered += chunk.toString()',
    '    const lines = buffered.split(/\\r?\\n/)',
    '    buffered = lines.pop() ?? \'\'',
    '    for (const line of lines) {',
    '      onLine?.(line)',
    '      if (!suppressedOutput.has(line)) {',
    '        target.write(`${line}\\n`)',
    '      }',
    '    }',
    '  })',
    '',
    '  stream.on(\'end\', () => {',
    '    if (buffered.length > 0) {',
    '      onLine?.(buffered)',
    '    }',
    '    if (buffered.length > 0 && !suppressedOutput.has(buffered)) {',
    '      target.write(buffered)',
    '    }',
    '  })',
    '}',
    '',
    'function extractNextConflictInfo(lines) {',
    '  if (framework !== \'next\' || mode !== \'dev\') {',
    '    return undefined',
    '  }',
    '',
    '  if (!lines.some(line => line.includes(\'Another next dev server is already running.\'))) {',
    '    return undefined',
    '  }',
    '',
    '  let pid',
    '  let dir',
    '',
    '  for (const line of lines) {',
    '    const match = line.match(/^- PID:\\s+(\\d+)\\s*$/)',
    '    if (match) {',
    '      pid = Number.parseInt(match[1], 10)',
    '      continue',
    '    }',
    '',
    '    const dirMatch = line.match(/^- Dir:\\s+(.+?)\\s*$/)',
    '    if (dirMatch) {',
    '      dir = dirMatch[1]',
    '    }',
    '  }',
    '',
    '  return typeof pid === \'number\' ? { pid, dir } : undefined',
    '}',
    '',
    'async function waitForProcessExit(pid, timeoutMs = 5000) {',
    '  const deadline = Date.now() + timeoutMs',
    '  while (Date.now() < deadline) {',
    '    try {',
    '      process.kill(pid, 0)',
    '    } catch (error) {',
    '      if (error && typeof error === \'object\' && \'code\' in error && error.code === \'ESRCH\') {',
    '        return true',
    '      }',
    '      throw error',
    '    }',
    '',
    '    await new Promise(resolve => setTimeout(resolve, 100))',
    '  }',
    '',
    '  return false',
    '}',
    '',
    'function inspectProcess(pid) {',
    '  try {',
    '    if (process.platform === \'linux\' && existsSync(`/proc/${pid}`)) {',
    '      return {',
    '        cwd: readlinkSync(`/proc/${pid}/cwd`),',
    '        args: readFileSync(`/proc/${pid}/cmdline`, \'utf8\').replaceAll(\'\\u0000\', \' \').trim(),',
    '      }',
    '    }',
    '  } catch {',
    '    // Fall through to the portable process inspection path below.',
    '  }',
    '',
    '  try {',
    '    return {',
    '      args: execFileSync(\'ps\', [\'-p\', String(pid), \'-o\', \'args=\'], {',
    '        encoding: \'utf8\',',
    '      }).trim(),',
    '    }',
    '  } catch {',
    '    return undefined',
    '  }',
    '}',
    '',
    'function isOwnedNextDevServer(pid, reportedDir) {',
    '  const expectedDir = typeof reportedDir === \'string\' ? resolve(reportedDir) : undefined',
    '  if (expectedDir && expectedDir !== projectRoot) {',
    '    return false',
    '  }',
    '',
    '  const details = inspectProcess(pid)',
    '  if (!details) {',
    '    return expectedDir === projectRoot',
    '  }',
    '',
    '  const argsMatch = details.args.includes(\'next\') && details.args.includes(\'dev\')',
    '  const cwdMatches = typeof details.cwd === \'string\' && resolve(details.cwd) === projectRoot',
    '  const argsReferenceProject = details.args.includes(projectRoot)',
    '',
    '  return argsMatch && (cwdMatches || argsReferenceProject || expectedDir === projectRoot)',
    '}',
    '',
    'async function stopStaleNextDevServer(pid, reportedDir, force = false) {',
    '  if (!Number.isInteger(pid) || pid <= 0 || pid === process.pid) {',
    '    return false',
    '  }',
    '',
    '  if (!isOwnedNextDevServer(pid, reportedDir)) {',
    '    return false',
    '  }',
    '',
    '  if (!force) {',
    '    return false',
    '  }',
    '',
    '  try {',
    '    process.kill(pid, \'SIGTERM\')',
    '  } catch (error) {',
    '    if (error && typeof error === \'object\' && \'code\' in error && error.code === \'ESRCH\') {',
    '      return true',
    '    }',
    '    return false',
    '  }',
    '',
    '  return waitForProcessExit(pid)',
    '}',
    '',
    'if (!existsSync(binaryPath)) {',
    '  console.error(`[holo] Missing framework binary "${commandName}" for "${framework}". Run your package manager install first.`)',
    '  process.exit(1)',
    '}',
    '',
    'let child = null',
    'let forwardedSignal = null',
    '',
    'function detachSignalForwarders() {',
    '  process.removeListener(\'SIGINT\', onSigint)',
    '  process.removeListener(\'SIGTERM\', onSigterm)',
    '}',
    '',
    'function forwardSignal(signal) {',
    '  if (forwardedSignal || !child || child.exitCode !== null) {',
    '    return',
    '  }',
    '',
    '  forwardedSignal = signal',
    '  child.kill(signal)',
    '}',
    '',
    'function onSigint() {',
    '  detachSignalForwarders()',
    '  forwardSignal(\'SIGINT\')',
    '}',
    '',
    'function onSigterm() {',
    '  detachSignalForwarders()',
    '  forwardSignal(\'SIGTERM\')',
    '}',
    '',
    'process.on(\'SIGINT\', onSigint)',
    'process.on(\'SIGTERM\', onSigterm)',
    '',
    'async function run() {',
    '  let restartedAfterConflict = false',
    '  const maxStderrLines = 200',
    '',
    '  while (true) {',
    '    const stderrLines = []',
    '    const childEnv = { ...process.env }',
    '    if (existsSync(runtimeSchemaPath)) {',
    '      const preload = `--import=${pathToFileURL(runtimeSchemaPath).href}`',
      '      childEnv.NODE_OPTIONS = childEnv.NODE_OPTIONS',
      '        ? `${childEnv.NODE_OPTIONS} ${preload}`',
      '        : preload',
    '    }',
    '    child = spawn(binaryPath, commandArgs, {',
    '      cwd: projectRoot,',
    '      env: childEnv,',
    '      stdio: [\'inherit\', \'pipe\', \'pipe\'],',
    '    })',
    '    forwardedSignal = null',
    '',
    '    pipeOutput(child.stdout, process.stdout)',
    '    pipeOutput(child.stderr, process.stderr, line => {',
    '      if (stderrLines.length >= maxStderrLines) {',
    '        stderrLines.shift()',
    '      }',
    '      stderrLines.push(line)',
    '    })',
    '',
    '    const result = await new Promise((resolve, reject) => {',
    '      child.on(\'error\', reject)',
    '      child.on(\'close\', (code, signal) => resolve({ code, signal }))',
    '    })',
    '',
    '    if (result.code === 0) {',
    '      process.exit(0)',
    '    }',
    '',
    '    const conflictInfo = extractNextConflictInfo(stderrLines)',
    '    if (!restartedAfterConflict && conflictInfo) {',
    '      const stopped = await stopStaleNextDevServer(conflictInfo.pid, conflictInfo.dir)',
    '      if (stopped) {',
    '        restartedAfterConflict = true',
    '        console.error(`[holo] Stopped stale Next dev server ${conflictInfo.pid}. Restarting dev server.`)',
    '        continue',
    '      }',
    '',
    '      // Another dev server is already running (possibly in a different directory).',
    '      // Next.js already printed the conflict message with instructions to kill it.',
    '      // Exit gracefully to avoid noisy npm/bun error cascades.',
    '      process.exit(0)',
    '    }',
    '',
    '    if (result.signal) {',
    '      detachSignalForwarders()',
    '      process.kill(process.pid, result.signal)',
    '    } else {',
    '      process.exit(result.code ?? 1)',
    '    }',
    '  }',
    '}',
    '',
    'run().catch((error) => {',
    '  console.error(error instanceof Error ? error.message : String(error))',
    '  process.exit(1)',
    '})',
    '',
  ].join('\n')
}
