import {
  previewMail,
  renderMailPreview,
  sendMail,
} from './runtime'

export { defineMailConfig } from '@holo-js/config'
export type { HoloMailConfig, NormalizedHoloMailConfig } from '@holo-js/config'

export {
  attachContent,
  attachFromPath,
  attachFromStorage,
  createAttachmentMetadata,
  createAttachmentResolutionPlan,
  createAttachmentResolutionPlans,
  defineMail,
  inferMimeTypeFromName,
  isMailDefinition,
  isAttachmentQueueSafe,
  mailInternals,
  mergeMailDefinitionInputs,
  normalizeMailDefinition,
  resolveAttachmentDefinition,
  resolveNormalizedAttachment,
} from './contracts'
export type {
  BuiltInMailDriverRegistry,
  HoloMailDriverRegistry,
  MailAddress,
  MailAddressInput,
  MailAttachmentBase,
  MailAttachmentContent,
  MailAttachmentDisposition,
  MailAttachmentHelperOptions,
  MailAttachmentInput,
  MailAttachmentMetadata,
  MailAttachmentResolutionContext,
  MailAttachmentResolutionPlan,
  MailContentAttachment,
  MailContentAttachmentHelperOptions,
  MailContentSourceKind,
  MailDefinition,
  MailDefinitionInput,
  MailDelayValue,
  MailDriver,
  MailDriverExecutionContext,
  MailDriverName,
  MailJsonObject,
  MailJsonValue,
  MailOverrideInput,
  MailPathAttachment,
  MailPreviewFormat,
  MailPreviewInput,
  MailPreviewResult,
  MailPriority,
  MailQueueOptions,
  MailRecipientsInput,
  MailRenderPreviewInput,
  MailRenderSource,
  MailPreviewPolicy,
  MailResolvableAttachment,
  MailResolvedAttachmentPayload,
  MailRuntimeBindings,
  MailSendInput,
  MailSendOptions,
  MailSendResult,
  MailStorageAttachment,
  MailStorageAttachmentHelperOptions,
  MailViewRenderInput,
  MailViewRenderer,
  PendingMailSend,
  RegisterMailDriverOptions,
  RegisteredMailDriver,
  ResolvedMail,
  ResolvedMailAttachment,
} from './contracts'
export type {
  FakeSentMail,
  MailPreviewArtifact,
} from './runtime'
export {
  getRegisteredMailDriver,
  listRegisteredMailDrivers,
  mailRegistryInternals,
  registerMailDriver,
  resetMailDriverRegistry,
} from './registry'
export {
  configureMailRuntime,
  getMailRuntimeBindings,
  listFakeSentMails,
  listPreviewMailArtifacts,
  getMailRuntime,
  MailError,
  MailPreviewDisabledError,
  MailPreviewFormatUnavailableError,
  MailSendError,
  mailRuntimeInternals,
  previewMail,
  renderMailPreview,
  resetFakeSentMails,
  resetMailRuntime,
  resetPreviewMailArtifacts,
  sendMail,
} from './runtime'

const mail = Object.freeze({
  previewMail,
  renderMailPreview,
  sendMail,
})

export default mail
