import type { AuthorizationFacade } from './contracts'

export {
  allow,
  deny,
  denyAsNotFound,
  isAuthorizationAbilityDefinition,
  isAuthorizationDecision,
  isAuthorizationPolicyDefinition,
  normalizeAuthorizationDecision,
  AuthorizationAbilityNotFoundError,
  AuthorizationActorContext,
  AuthorizationActorBuilder,
  AuthorizationAuthIntegrationMissingError,
  AuthorizationDecision,
  AuthorizationDecisionInput,
  AuthorizationDecisionStatus,
  AuthorizationError,
  AuthorizationAbilityBuilder,
  AuthorizationGuardActorContext,
  AuthorizationGuardNotFoundError,
  AuthorizationPolicyBeforeHandler,
  AuthorizationPolicyBuilder,
  AuthorizationPolicyDefinition,
  AuthorizationPolicyNotFoundError,
  AuthorizationPolicyRegistry,
  AuthorizationPolicyRegistryEntry,
  AuthorizationAbilityRegistry,
  AuthorizationAbilityRegistryEntry,
  AuthorizationFacade,
  AuthorizationPolicyTarget,
  AuthorizationTargetConstructor,
  AuthorizationTargetModel,
  AuthorizationTargetModelDefinition,
  AuthorizationTargetInstance,
  AbilityInput,
  HoloAbilityName,
  HoloAuthorizationGuardName,
  HoloPolicyName,
  PolicyActionFor,
  PolicyActionForPolicy,
  PolicyClassActionForPolicy,
  PolicyRecordActionForPolicy,
  PolicyInstanceForPolicy,
  PolicyTargetForPolicy,
  PolicyClassActionFor,
  PolicyRecordActionFor,
  type AuthorizationAbilityHandler,
  type AuthorizationPolicyClassHandler,
  type AuthorizationPolicyRecordHandler,
} from './contracts'
export {
  authorize,
  authorizationInternals,
  can,
  cannot,
  defineAbility,
  definePolicy,
  forUser,
  guard,
  inspect,
} from './runtime'

import { authorize, can, cannot, forUser, guard, inspect } from './runtime'

const authorization: AuthorizationFacade = Object.freeze({
  forUser,
  guard,
  authorize,
  can,
  cannot,
  inspect,
})

export default authorization
