import {
  collectMultiStringFlag,
  isInteractive,
  normalizeChoice,
  normalizeOptionalPackages,
  parseNumberFlag,
  parseTokens,
  promptChoice,
  promptOptionalPackages,
  resolveBooleanFlag,
  resolveNewProjectInput,
  resolveStringFlag,
  splitCsv,
} from './parsing'
import {
  createEnvRuntimeConfig,
  cacheProjectConfig,
  createRuntimeInvocation,
  dropAllTablesForFresh,
  getRuntimeEnvironment,
  getRuntimeFailureMessage,
  inferRuntimeMigrationName,
  mergeRuntimeDatabaseConfig,
  normalizeRuntimeMigration,
  parseBooleanEnv,
  resolveConfigModuleUrl,
  withRuntimeEnvironment,
} from './runtime'
import {
  buildQueueWorkArgs,
  collectQueueWatchRoots,
  getQueueRuntimeEnvironment,
  hasQueueRestartSignalSince,
  isQueueListenRelevantPath,
  readQueueRestartSignal,
  resolveCliEntrypointPath,
  resolveModuleExport,
  resolveQueueRestartSignalPath,
  resolveRunnableCliEntrypoint,
  runQueueClearCommand,
  runQueueFailedCommand,
  runQueueFlushCommand,
  runQueueForgetCommand,
  runQueueListen,
  runQueueRestartCommand,
  runQueueRetryCommand,
  runQueueWorkCommand,
  writeQueueRestartSignal,
} from './queue'
import {
  runBroadcastWorkCommand,
} from './broadcast'
import {
  runRateLimitClearCommand,
} from './security'
import {
  renderFailedJobsTableMigration,
  renderQueueTableMigration,
  resolveDatabaseQueueTables,
  runQueueFailedTableCommand,
  runQueueTableCommand,
} from './queue-migrations'
import {
  resolvePackageManagerCommand,
  resolvePackageManagerInstallInvocation,
  runProjectDependencyInstall,
  runProjectDevServer,
  runProjectLifecycleScript,
  runProjectPrepare,
  isIgnorableWatchError,
} from './dev'
import {
  runMakeBroadcast,
  runMakeChannel,
  runMakeEvent,
  runMakeFactory,
  runMakeJob,
  runMakeListener,
  runMakeMail,
  runMakeMigration,
  runMakeModel,
  runMakeObserver,
  runMakeSeeder,
} from './generators'
import { ensureAbsent, fileExists } from './fs-utils'
import { hasProjectDependency } from './package-json'
import {
  getRegistryMigrationSlug,
  hasRegisteredCreateTableMigration,
  hasRegisteredMigrationSlug,
  nextMigrationTemplate,
} from './migrations'
import {
  createAppCommandDefinition,
  createCommandContext,
  createInternalCommands,
  findCommand,
  findCommandConflict,
  commandTokens,
  printCommandHelp,
  printCommandList,
  resolvePackageManagerDevCommand,
  resolvePackageManagerInstallCommand,
} from './cli'

export const cliInternals = {
  cacheProjectConfig,
  createAppCommandDefinition,
  createCommandContext,
  createEnvRuntimeConfig,
  createInternalCommands,
  createRuntimeInvocation,
  buildQueueWorkArgs,
  collectQueueWatchRoots,
  collectMultiStringFlag,
  commandTokens,
  dropAllTablesForFresh,
  ensureAbsent,
  fileExists,
  findCommand,
  findCommandConflict,
  getQueueRuntimeEnvironment,
  getRegistryMigrationSlug,
  getRuntimeEnvironment,
  getRuntimeFailureMessage,
  hasProjectDependency,
  hasQueueRestartSignalSince,
  hasRegisteredCreateTableMigration,
  hasRegisteredMigrationSlug,
  inferRuntimeMigrationName,
  isIgnorableWatchError,
  isInteractive,
  isQueueListenRelevantPath,
  mergeRuntimeDatabaseConfig,
  nextMigrationTemplate,
  normalizeChoice,
  normalizeOptionalPackages,
  normalizeRuntimeMigration,
  parseBooleanEnv,
  parseNumberFlag,
  parseTokens,
  printCommandHelp,
  printCommandList,
  promptChoice,
  promptOptionalPackages,
  readQueueRestartSignal,
  renderFailedJobsTableMigration,
  renderQueueTableMigration,
  resolveBooleanFlag,
  resolveCliEntrypointPath,
  resolveConfigModuleUrl,
  resolveDatabaseQueueTables,
  resolveModuleExport,
  resolveNewProjectInput,
  resolvePackageManagerCommand,
  resolvePackageManagerDevCommand,
  resolvePackageManagerInstallCommand,
  resolvePackageManagerInstallInvocation,
  resolveQueueRestartSignalPath,
  resolveRunnableCliEntrypoint,
  resolveStringFlag,
  runMakeBroadcast,
  runMakeChannel,
  runMakeEvent,
  runMakeFactory,
  runMakeJob,
  runMakeListener,
  runMakeMail,
  runMakeMigration,
  runMakeModel,
  runMakeObserver,
  runMakeSeeder,
  runProjectDependencyInstall,
  runProjectDevServer,
  runProjectLifecycleScript,
  runProjectPrepare,
  runQueueClearCommand,
  runQueueFailedCommand,
  runQueueFailedTableCommand,
  runQueueFlushCommand,
  runQueueForgetCommand,
  runQueueListen,
  runQueueRestartCommand,
  runQueueRetryCommand,
  runQueueTableCommand,
  runQueueWorkCommand,
  runBroadcastWorkCommand,
  runRateLimitClearCommand,
  splitCsv,
  withRuntimeEnvironment,
  writeQueueRestartSignal,
}
