import { normalizeHoloProjectConfig, type NormalizedHoloProjectConfig } from '@holo-js/db'
export type {
  CliModelReference,
  DiscoveredAppCommand,
  EventsInstallResult,
  GeneratedCommandRegistryEntry,
  GeneratedEventRegistryEntry,
  GeneratedJobRegistryEntry,
  GeneratedListenerRegistryEntry,
  GeneratedMigrationRegistryEntry,
  GeneratedModelRegistryEntry,
  GeneratedProjectRegistry,
  GeneratedSeederRegistryEntry,
  ProjectScaffoldOptions,
  QueueInstallResult,
  SupportedQueueInstallerDriver,
  SupportedScaffoldFramework,
  SupportedScaffoldOptionalPackage,
  SupportedScaffoldPackageManager,
  SupportedScaffoldStorageDisk,
} from './project/shared'

import {
  defaultProjectConfig,
  ensureGeneratedSchemaPlaceholder,
  ensureProjectConfig,
  loadProjectConfig,
  readTextFile,
  resolveGeneratedSchemaPath,
  serializeDatabaseConfig,
  serializeProjectConfig,
  writeProjectConfig,
} from './project/config'
import {
  collectImportedBindingsBySource,
  discoverAppCommands,
  extractListensToItems,
  loadRegisteredMigrations,
  loadRegisteredModels,
  loadRegisteredSeeders,
  prepareProjectDiscovery,
  resolveListenerEventNamesForDiscovery,
  resolveListenerEventNamesFromSource,
  resolveNamedExport,
  resolveNamedExportEntry,
} from './project/discovery'
import {
  ensureGeneratedRegistryOwnership,
  getConfigExtensionPriority,
  isGeneratedProjectRegistry,
  loadGeneratedProjectRegistry,
  renderGeneratedIndexModule,
  renderGeneratedModule,
  renderGeneratedTsconfig,
  writeGeneratedProjectRegistry,
} from './project/registry'
import {
  bundleProjectModule,
  findProjectRoot,
  resetProjectModuleBundlerForTesting,
  resolveProjectPackageImportSpecifier,
  setProjectModuleBundlerForTesting,
  writeTextFile,
} from './project/runtime'
import {
  installEventsIntoProject,
  installQueueIntoProject,
  inferConnectionDriver,
  inferDatabaseDriverFromUrl,
  hasLoadedConfigFile,
  isSupportedQueueInstallerDriver,
  normalizeScaffoldOptionalPackages,
  renderFrameworkFiles,
  renderFrameworkRunner,
  renderMediaConfig,
  renderQueueConfig,
  renderQueueEnvFiles,
  renderScaffoldAppConfig,
  renderScaffoldDatabaseConfig,
  renderScaffoldEnvFiles,
  renderScaffoldGitignore,
  renderScaffoldPackageJson,
  renderScaffoldTsconfig,
  renderStorageConfig,
  resolveDefaultDatabaseUrl,
  resolvePackageManagerVersion,
  sanitizePackageName,
  scaffoldProject,
  syncManagedDriverDependencies,
  upsertEventsPackageDependency,
} from './project/scaffold'
import {
  CLI_RUNTIME_ROOT,
  HOLO_RUNTIME_ROOT,
  isSupportedScaffoldFramework,
  isSupportedScaffoldOptionalPackage,
  isSupportedScaffoldPackageManager,
  isSupportedScaffoldStorageDisk,
  makeProjectRelativePath,
  resolveDefaultArtifactPath,
  stripFileExtension,
} from './project/shared'

export function upsertProjectRegistration(
  config: NormalizedHoloProjectConfig,
  key: 'models' | 'migrations' | 'seeders',
  entry: string,
): NormalizedHoloProjectConfig {
  const next = {
    paths: config.paths,
    ...(config.database ? { database: config.database } : {}),
    models: [...config.models],
    migrations: [...config.migrations],
    seeders: [...config.seeders],
  }

  if (!next[key].includes(entry)) {
    next[key].push(entry)
    next[key].sort((left, right) => left.localeCompare(right))
  }

  return normalizeHoloProjectConfig(next)
}

export {
  bundleProjectModule,
  CLI_RUNTIME_ROOT,
  defaultProjectConfig,
  discoverAppCommands,
  ensureGeneratedSchemaPlaceholder,
  ensureProjectConfig,
  findProjectRoot,
  HOLO_RUNTIME_ROOT,
  installEventsIntoProject,
  installQueueIntoProject,
  loadGeneratedProjectRegistry,
  loadProjectConfig,
  loadRegisteredMigrations,
  loadRegisteredModels,
  loadRegisteredSeeders,
  makeProjectRelativePath,
  prepareProjectDiscovery,
  readTextFile,
  resolveDefaultArtifactPath,
  resolveGeneratedSchemaPath,
  resolveProjectPackageImportSpecifier,
  scaffoldProject,
  stripFileExtension,
  syncManagedDriverDependencies,
  writeProjectConfig,
  writeTextFile,
}

export const projectInternals = {
  ensureGeneratedRegistryOwnership,
  getConfigExtensionPriority,
  isSupportedScaffoldFramework,
  isSupportedScaffoldPackageManager,
  isSupportedScaffoldStorageDisk,
  isGeneratedProjectRegistry,
  loadGeneratedProjectRegistry,
  renderFrameworkRunner,
  renderFrameworkFiles,
  renderGeneratedIndexModule,
  renderGeneratedModule,
  renderGeneratedTsconfig,
  renderScaffoldAppConfig,
  renderScaffoldDatabaseConfig,
  renderScaffoldEnvFiles,
  renderScaffoldGitignore,
  renderScaffoldPackageJson,
  renderScaffoldTsconfig,
  renderQueueConfig,
  renderQueueEnvFiles,
  renderStorageConfig,
  renderMediaConfig,
  installEventsIntoProject,
  installQueueIntoProject,
  collectImportedBindingsBySource,
  resolveProjectPackageImportSpecifier,
  resolveListenerEventNamesForDiscovery,
  resolveListenerEventNamesFromSource,
  extractListensToItems,
  hasLoadedConfigFile,
  inferConnectionDriver,
  inferDatabaseDriverFromUrl,
  upsertEventsPackageDependency,
  syncManagedDriverDependencies,
  resolveDefaultDatabaseUrl,
  resolvePackageManagerVersion,
  isSupportedQueueInstallerDriver,
  resetProjectModuleBundlerForTesting,
  sanitizePackageName,
  setProjectModuleBundlerForTesting,
  serializeDatabaseConfig,
  serializeProjectConfig,
  scaffoldProject,
  isSupportedScaffoldOptionalPackage,
  normalizeScaffoldOptionalPackages,
  resolveNamedExport,
  resolveNamedExportEntry,
  upsertProjectRegistration,
  writeGeneratedProjectRegistry,
}
