import { normalizeHoloProjectConfig, type NormalizedHoloProjectConfig } from '@holo-js/db'
export type {
  AuthInstallResult,
  AuthNotificationsPublishResult,
  BroadcastInstallResult,
  CacheInstallResult,
  CliModelReference,
  DiscoveredAppCommand,
  EventsInstallResult,
  GeneratedAuthorizationAbilityRegistryEntry,
  GeneratedAuthorizationPolicyRegistryEntry,
  GeneratedCommandRegistryEntry,
  GeneratedEventRegistryEntry,
  GeneratedJobRegistryEntry,
  GeneratedListenerRegistryEntry,
  GeneratedMigrationRegistryEntry,
  GeneratedModelRegistryEntry,
  GeneratedProjectRegistry,
  GeneratedSeederRegistryEntry,
  MailInstallResult,
  MediaInstallResult,
  NotificationsInstallResult,
  ProjectScaffoldOptions,
  QueueInstallResult,
  SupportedCacheInstallerDriver,
  SupportedQueueInstallerDriver,
  SupportedScaffoldFramework,
  SupportedScaffoldOptionalPackage,
  SupportedScaffoldPackageManager,
  SupportedScaffoldStorageDisk,
} from './project/shared'
export type {
  HoloPluginBroadcastContributions,
  HoloPluginCacheContributions,
  HoloPluginCliContributions,
  HoloPluginConfigContributions,
  HoloPluginContributions,
  HoloPluginDefinition,
  HoloPluginDependencyContributions,
  HoloPluginMailContributions,
  HoloPluginMigrationContributions,
  HoloPluginNotificationContributions,
  HoloPluginQueueContributions,
  HoloPluginRuntimeContributions,
  LoadedHoloPlugin,
  ResolvedProjectPlugin,
} from './project/plugins'

import {
  defaultProjectConfig,
  ensureGeneratedSchemaPlaceholder,
  ensureProjectConfig,
  loadProjectConfig,
  readTextFile,
  resolveGeneratedSchemaPath,
  serializeDatabaseConfig,
  serializeProjectConfig,
  writeProjectConfig,
} from './project/config'
import {
  collectImportedBindingsBySource,
  discoverAppCommands,
  extractListensToItems,
  loadRegisteredMigrations,
  loadRegisteredModels,
  loadRegisteredSeeders,
  prepareProjectDiscovery,
  resolveListenerEventNamesForDiscovery,
  resolveListenerEventNamesFromSource,
  resolveNamedExport,
  resolveNamedExportEntry,
} from './project/discovery'
import {
  ensureGeneratedRegistryOwnership,
  getConfigExtensionPriority,
  isGeneratedProjectRegistry,
  loadGeneratedProjectRegistry,
  renderGeneratedAuthorizationRegistry,
  renderGeneratedAuthorizationTypes,
  renderGeneratedIndexModule,
  renderGeneratedModule,
  renderGeneratedTsconfig,
  writeGeneratedProjectRegistry,
} from './project/registry'
import {
  bundleProjectModule,
  findProjectRoot,
  resetProjectModuleBundlerForTesting,
  resolveProjectPackageImportSpecifier,
  setProjectModuleBundlerForTesting,
  writeTextFile,
} from './project/runtime'
import {
  installAuthIntoProject,
  installAuthorizationIntoProject,
  installBroadcastIntoProject,
  installCacheIntoProject,
  installEventsIntoProject,
  installMailIntoProject,
  installMediaIntoProject,
  installNotificationsIntoProject,
  publishAuthNotificationsIntoProject,
  installQueueIntoProject,
  installSecurityIntoProject,
  inferConnectionDriver,
  inferDatabaseDriverFromUrl,
  hasLoadedConfigFile,
  injectBroadcastAuthEndpoint,
  isSupportedCacheInstallerDriver,
  isSupportedQueueInstallerDriver,
  authFeaturesRequireConfigUpdate,
  detectAuthInstallFeaturesFromConfig,
  normalizeScaffoldOptionalPackages,
  renderFrameworkFiles,
  renderFrameworkRunner,
  renderFrameworkRunnerForDescriptor,
  renderAuthConfig,
  renderAuthMigration,
  renderAuthEnvFiles,
  renderAuthProviderRouteFiles,
  renderAuthUserModel,
  renderMediaConfig,
  renderMailConfig,
  renderCacheConfig,
  renderCorsConfig,
  renderSecurityConfig,
  renderQueueConfig,
  renderCacheEnvFiles,
  renderEnvFileContents,
  renderRedisConfig,
  renderQueueEnvFiles,
  normalizeScaffoldEnvSegments,
  renderScaffoldAppConfig,
  renderScaffoldDatabaseConfig,
  renderScaffoldEnvFiles,
  renderScaffoldGitignore,
  renderScaffoldPackageJson,
  renderScaffoldTsconfig,
  renderVSCodeSettings,
  renderSessionConfig,
  renderStorageConfig,
  resolveBroadcastConfigTargetPath,
  resolveDefaultDatabaseUrl,
  resolvePackageManagerVersion,
  sanitizePackageName,
  scaffoldProject,
  syncManagedDriverDependencies,
  upsertAuthPackageDependencies,
  upsertCachePackageDependencies,
  upsertEventsPackageDependency,
  upsertMailPackageDependency,
  upsertMediaPackageDependency,
  upsertSecurityPackageDependency,
} from './project/scaffold'
import {
  CLI_RUNTIME_ROOT,
  HOLO_RUNTIME_ROOT,
  isSupportedScaffoldFramework,
  isSupportedScaffoldOptionalPackage,
  isSupportedScaffoldPackageManager,
  isSupportedScaffoldStorageDisk,
  makeProjectRelativePath,
  resolveDefaultArtifactPath,
  stripFileExtension,
} from './project/shared'
import {
  activateProjectPlugin,
  deactivateProjectPlugin,
  defineHoloPlugin,
  loadHoloPluginFromPackage,
  loadProjectPluginCommands,
  loadProjectPluginFrameworkDescriptors,
  normalizeHoloPluginDefinition,
  readProjectPluginNames,
  resolveProjectPlugins,
  writeProjectPluginNames,
} from './project/plugins'

export function upsertProjectRegistration(
  config: NormalizedHoloProjectConfig,
  key: 'models' | 'migrations' | 'seeders',
  entry: string,
): NormalizedHoloProjectConfig {
  const next = {
    paths: config.paths,
    ...(config.database ? { database: config.database } : {}),
    models: [...config.models],
    migrations: [...config.migrations],
    seeders: [...config.seeders],
  }

  if (!next[key].includes(entry)) {
    next[key].push(entry)
    next[key].sort((left, right) => left.localeCompare(right))
  }

  return normalizeHoloProjectConfig(next)
}

export {
  bundleProjectModule,
  CLI_RUNTIME_ROOT,
  defaultProjectConfig,
  defineHoloPlugin,
  discoverAppCommands,
  ensureGeneratedSchemaPlaceholder,
  ensureProjectConfig,
  findProjectRoot,
  HOLO_RUNTIME_ROOT,
  installAuthIntoProject,
  installAuthorizationIntoProject,
  installBroadcastIntoProject,
  installCacheIntoProject,
  installEventsIntoProject,
  installMailIntoProject,
  installMediaIntoProject,
  installNotificationsIntoProject,
  publishAuthNotificationsIntoProject,
  installQueueIntoProject,
  installSecurityIntoProject,
  loadHoloPluginFromPackage,
  loadProjectPluginCommands,
  loadProjectPluginFrameworkDescriptors,
  loadGeneratedProjectRegistry,
  loadProjectConfig,
  loadRegisteredMigrations,
  loadRegisteredModels,
  loadRegisteredSeeders,
  makeProjectRelativePath,
  prepareProjectDiscovery,
  readProjectPluginNames,
  readTextFile,
  renderFrameworkRunner,
  renderFrameworkRunnerForDescriptor,
  resolveDefaultArtifactPath,
  resolveGeneratedSchemaPath,
  resolveProjectPackageImportSpecifier,
  resolveProjectPlugins,
  scaffoldProject,
  stripFileExtension,
  syncManagedDriverDependencies,
  writeProjectConfig,
  writeProjectPluginNames,
  writeTextFile,
}

export const projectInternals = {
  ensureGeneratedRegistryOwnership,
  getConfigExtensionPriority,
  isSupportedScaffoldFramework,
  isSupportedScaffoldPackageManager,
  isSupportedScaffoldStorageDisk,
  isGeneratedProjectRegistry,
  loadGeneratedProjectRegistry,
  renderFrameworkRunner,
  renderFrameworkRunnerForDescriptor,
  renderFrameworkFiles,
  renderGeneratedIndexModule,
  renderGeneratedAuthorizationRegistry,
  renderGeneratedAuthorizationTypes,
  renderGeneratedModule,
  renderGeneratedTsconfig,
  authFeaturesRequireConfigUpdate,
  detectAuthInstallFeaturesFromConfig,
  renderAuthConfig,
  renderAuthMigration,
  renderAuthEnvFiles,
  renderAuthProviderRouteFiles,
  renderAuthUserModel,
  renderScaffoldAppConfig,
  renderScaffoldDatabaseConfig,
  renderScaffoldEnvFiles,
  renderScaffoldGitignore,
  renderScaffoldPackageJson,
  renderScaffoldTsconfig,
  renderVSCodeSettings,
  renderCacheConfig,
  renderCorsConfig,
  renderQueueConfig,
  renderCacheEnvFiles,
  renderEnvFileContents,
  renderRedisConfig,
  renderQueueEnvFiles,
  normalizeScaffoldEnvSegments,
  renderSessionConfig,
  renderStorageConfig,
  renderMediaConfig,
  renderMailConfig,
  renderSecurityConfig,
  installAuthIntoProject,
  installAuthorizationIntoProject,
  installBroadcastIntoProject,
  installCacheIntoProject,
  installEventsIntoProject,
  installMailIntoProject,
  installMediaIntoProject,
  installNotificationsIntoProject,
  publishAuthNotificationsIntoProject,
  installQueueIntoProject,
  installSecurityIntoProject,
  collectImportedBindingsBySource,
  resolveProjectPackageImportSpecifier,
  resolveListenerEventNamesForDiscovery,
  resolveListenerEventNamesFromSource,
  extractListensToItems,
  hasLoadedConfigFile,
  inferConnectionDriver,
  inferDatabaseDriverFromUrl,
  injectBroadcastAuthEndpoint,
  resolveBroadcastConfigTargetPath,
  upsertCachePackageDependencies,
  upsertEventsPackageDependency,
  upsertMailPackageDependency,
  upsertMediaPackageDependency,
  upsertSecurityPackageDependency,
  upsertAuthPackageDependencies,
  syncManagedDriverDependencies,
  resolveDefaultDatabaseUrl,
  resolvePackageManagerVersion,
  isSupportedQueueInstallerDriver,
  isSupportedCacheInstallerDriver,
  resetProjectModuleBundlerForTesting,
  sanitizePackageName,
  setProjectModuleBundlerForTesting,
  serializeDatabaseConfig,
  serializeProjectConfig,
  scaffoldProject,
  isSupportedScaffoldOptionalPackage,
  normalizeScaffoldOptionalPackages,
  resolveNamedExport,
  resolveNamedExportEntry,
  upsertProjectRegistration,
  writeGeneratedProjectRegistry,
  activateProjectPlugin,
  deactivateProjectPlugin,
  normalizeHoloPluginDefinition,
}
