import { SchemaError } from '../core/errors'
import type { AnyColumnDefinition, IdGenerationStrategy, LogicalColumnKind } from './types'

export type SchemaDialectName = 'sqlite' | 'postgres' | 'mysql'

type ColumnTypeResolver = (column: AnyColumnDefinition) => string
type DialectTypeEntry = string | ColumnTypeResolver
type DialectTypeMapping = Readonly<Record<LogicalColumnKind, DialectTypeEntry>>

type DialectIdStrategyMap = Readonly<Record<IdGenerationStrategy, string>>

export const DIALECT_ID_STRATEGY_MAP: Readonly<Record<SchemaDialectName, DialectIdStrategyMap>> = Object.freeze({
  sqlite: Object.freeze({
    autoIncrement: 'INTEGER',
    uuid: 'TEXT',
    ulid: 'TEXT',
    snowflake: 'TEXT',
  }),
  postgres: Object.freeze({
    autoIncrement: 'BIGINT GENERATED BY DEFAULT AS IDENTITY',
    uuid: 'UUID',
    ulid: 'VARCHAR(26)',
    snowflake: 'VARCHAR(32)',
  }),
  mysql: Object.freeze({
    autoIncrement: 'BIGINT AUTO_INCREMENT',
    uuid: 'CHAR(36)',
    ulid: 'CHAR(26)',
    snowflake: 'VARCHAR(32)',
  }),
})

export function resolveDialectIdStrategyType(
  dialect: SchemaDialectName,
  strategy: IdGenerationStrategy,
): string {
  return DIALECT_ID_STRATEGY_MAP[dialect][strategy]
}

function compileIdType(dialect: SchemaDialectName, column: AnyColumnDefinition): string {
  if (column.idStrategy !== 'autoIncrement') {
    return 'BIGINT'
  }

  return resolveDialectIdStrategyType(dialect, 'autoIncrement')
}

function compileEnumType(column: AnyColumnDefinition): string {
  if (!column.enumValues || column.enumValues.length === 0) {
    throw new SchemaError('MySQL enum columns require enum values.')
  }

  return `ENUM(${column.enumValues.map((value: string) => `'${String(value).replaceAll('\'', '\'\'')}'`).join(', ')})`
}

function compileVectorType(column: AnyColumnDefinition): string {
  if (!column.vectorDimensions) {
    throw new SchemaError('Postgres vector columns require explicit dimensions.')
  }

  return `VECTOR(${column.vectorDimensions})`
}

function unsupportedType(message: string): ColumnTypeResolver {
  return () => {
    throw new SchemaError(message)
  }
}

const SQLITE_LOGICAL_TYPE_MAP: DialectTypeMapping = {
  id: column => compileIdType('sqlite', column),
  integer: 'INTEGER',
  bigInteger: 'INTEGER',
  string: 'TEXT',
  text: 'TEXT',
  boolean: 'INTEGER',
  real: 'REAL',
  decimal: 'NUMERIC',
  date: 'TEXT',
  datetime: 'TEXT',
  timestamp: 'TEXT',
  json: 'TEXT',
  blob: 'BLOB',
  uuid: DIALECT_ID_STRATEGY_MAP.sqlite.uuid,
  ulid: DIALECT_ID_STRATEGY_MAP.sqlite.ulid,
  snowflake: DIALECT_ID_STRATEGY_MAP.sqlite.snowflake,
  vector: unsupportedType('SQLite does not support logical vector columns.'),
  enum: 'TEXT',
}

const POSTGRES_LOGICAL_TYPE_MAP: DialectTypeMapping = {
  id: column => compileIdType('postgres', column),
  integer: 'INTEGER',
  bigInteger: 'BIGINT',
  string: 'VARCHAR(255)',
  text: 'TEXT',
  boolean: 'BOOLEAN',
  real: 'DOUBLE PRECISION',
  decimal: 'NUMERIC',
  date: 'DATE',
  datetime: 'TIMESTAMP',
  timestamp: 'TIMESTAMP',
  json: 'JSONB',
  blob: 'BYTEA',
  uuid: DIALECT_ID_STRATEGY_MAP.postgres.uuid,
  ulid: DIALECT_ID_STRATEGY_MAP.postgres.ulid,
  snowflake: DIALECT_ID_STRATEGY_MAP.postgres.snowflake,
  vector: compileVectorType,
  enum: 'TEXT',
}

const MYSQL_LOGICAL_TYPE_MAP: DialectTypeMapping = {
  id: column => compileIdType('mysql', column),
  integer: 'INT',
  bigInteger: 'BIGINT',
  string: 'VARCHAR(255)',
  text: 'TEXT',
  boolean: 'TINYINT(1)',
  real: 'DOUBLE',
  decimal: 'DECIMAL(10, 2)',
  date: 'DATE',
  datetime: 'DATETIME',
  timestamp: 'TIMESTAMP',
  json: 'JSON',
  blob: 'BLOB',
  uuid: DIALECT_ID_STRATEGY_MAP.mysql.uuid,
  ulid: DIALECT_ID_STRATEGY_MAP.mysql.ulid,
  snowflake: DIALECT_ID_STRATEGY_MAP.mysql.snowflake,
  vector: unsupportedType('MySQL does not support logical vector columns.'),
  enum: compileEnumType,
}

export const DIALECT_LOGICAL_TYPE_MAP: Readonly<Record<SchemaDialectName, DialectTypeMapping>> = Object.freeze({
  sqlite: Object.freeze(SQLITE_LOGICAL_TYPE_MAP),
  postgres: Object.freeze(POSTGRES_LOGICAL_TYPE_MAP),
  mysql: Object.freeze(MYSQL_LOGICAL_TYPE_MAP),
})

export function resolveDialectColumnType(
  dialect: SchemaDialectName,
  column: AnyColumnDefinition,
): string {
  const entry = DIALECT_LOGICAL_TYPE_MAP[dialect][column.kind]
  if (typeof entry === 'undefined') {
    throw new SchemaError(`Unsupported logical column kind "${String(column.kind)}" for ${dialect === 'sqlite' ? 'SQLite' : dialect === 'postgres' ? 'Postgres' : 'MySQL'} compilation.`)
  }

  return typeof entry === 'function' ? entry(column) : entry
}
