import { describe, expect, it } from 'vitest'
import {
  DIALECT_ID_STRATEGY_MAP,
  DIALECT_LOGICAL_TYPE_MAP,
  SchemaError,
  column,
  resolveDialectColumnType,
  resolveDialectIdStrategyType } from '../src'

describe('schema type mapping', () => {
  it('defines explicit logical type mappings for every supported schema dialect', () => {
    expect(Object.keys(DIALECT_LOGICAL_TYPE_MAP).sort()).toEqual(['mysql', 'postgres', 'sqlite'])
    expect(resolveDialectColumnType('sqlite', column.boolean().toDefinition({ name: 'active' }))).toBe('INTEGER')
    expect(resolveDialectColumnType('postgres', column.uuid().toDefinition({ name: 'publicId' }))).toBe('UUID')
    expect(resolveDialectColumnType('mysql', column.timestamp().toDefinition({ name: 'createdAt' }))).toBe('TIMESTAMP')
  })

  it('handles dynamic id, enum, and vector mappings through the shared resolver', () => {
    expect(resolveDialectColumnType('postgres', column.id().toDefinition({ name: 'id' }))).toBe('BIGINT GENERATED BY DEFAULT AS IDENTITY')
    expect(resolveDialectColumnType('mysql', column.id().toDefinition({ name: 'id' }))).toBe('BIGINT AUTO_INCREMENT')
    expect(resolveDialectColumnType('mysql', column.enum(['draft', 'published'] as const).toDefinition({ name: 'status' }))).toBe(
      'ENUM(\'draft\', \'published\')',
    )
    expect(resolveDialectColumnType('postgres', column.vector({ dimensions: 3 }).toDefinition({ name: 'embedding' }))).toBe('VECTOR(3)')
  })

  it('defines explicit ID strategy mappings for every schema dialect', () => {
    expect(DIALECT_ID_STRATEGY_MAP).toEqual({
      sqlite: {
        autoIncrement: 'INTEGER',
        uuid: 'TEXT',
        ulid: 'TEXT',
        snowflake: 'TEXT' },
      postgres: {
        autoIncrement: 'BIGINT GENERATED BY DEFAULT AS IDENTITY',
        uuid: 'UUID',
        ulid: 'VARCHAR(26)',
        snowflake: 'VARCHAR(32)' },
      mysql: {
        autoIncrement: 'BIGINT AUTO_INCREMENT',
        uuid: 'CHAR(36)',
        ulid: 'CHAR(26)',
        snowflake: 'VARCHAR(32)' } })

    expect(resolveDialectIdStrategyType('sqlite', 'autoIncrement')).toBe('INTEGER')
    expect(resolveDialectIdStrategyType('postgres', 'uuid')).toBe('UUID')
    expect(resolveDialectIdStrategyType('postgres', 'ulid')).toBe('VARCHAR(26)')
    expect(resolveDialectIdStrategyType('mysql', 'snowflake')).toBe('VARCHAR(32)')
  })

  it('fails closed for unsupported dialect-specific logical type combinations', () => {
    expect(() => resolveDialectColumnType('sqlite', column.vector({ dimensions: 3 }).toDefinition({ name: 'embedding' }))).toThrow(SchemaError)
    expect(() => resolveDialectColumnType('mysql', column.vector({ dimensions: 3 }).toDefinition({ name: 'embedding' }))).toThrow(SchemaError)
    expect(() => resolveDialectColumnType('postgres', {
      kind: 'vector',
      name: 'embedding',
      nullable: false,
      hasDefault: false,
      generated: false,
      primaryKey: false,
      unique: false,
      vectorDimensions: 0 })).toThrow('Postgres vector columns require explicit dimensions.')
    expect(() => resolveDialectColumnType('mysql', {
      kind: 'enum',
      name: 'status',
      nullable: false,
      hasDefault: false,
      generated: false,
      primaryKey: false,
      unique: false,
      enumValues: [] })).toThrow('MySQL enum columns require enum values.')
  })
})
