import { resolve } from 'node:path'
import { defineConfig } from 'vitest/config'

const includeCliIntegration = process.env.HOLO_CLI_INCLUDE_INTEGRATION === '1'

export default defineConfig({
  resolve: {
    alias: [
      { find: '@holo-js/auth/config', replacement: resolve(__dirname, '../auth/src/config.ts') },
      { find: '@holo-js/broadcast/config', replacement: resolve(__dirname, '../broadcast/src/config.ts') },
      { find: '@holo-js/cache/config', replacement: resolve(__dirname, '../cache/src/config.ts') },
      { find: '@holo-js/db/config', replacement: resolve(__dirname, '../db/src/databaseConfig.ts') },
      { find: '@holo-js/mail/config', replacement: resolve(__dirname, '../mail/src/config.ts') },
      { find: '@holo-js/media/config', replacement: resolve(__dirname, '../media/src/projectConfig.ts') },
      { find: '@holo-js/notifications/config', replacement: resolve(__dirname, '../notifications/src/config.ts') },
      { find: '@holo-js/queue/config', replacement: resolve(__dirname, '../queue/src/config.ts') },
      { find: '@holo-js/security/config', replacement: resolve(__dirname, '../security/src/config.ts') },
      { find: '@holo-js/session/config', replacement: resolve(__dirname, '../session/src/config.ts') },
      { find: '@holo-js/storage/config', replacement: resolve(__dirname, '../storage/src/config.ts') },
      { find: '@holo-js/security/drivers/redis-adapter', replacement: resolve(__dirname, '../security/src/drivers/redis-adapter.ts') },
      { find: '@holo-js/session/drivers/redis-adapter', replacement: resolve(__dirname, '../session/src/drivers/redis-adapter.ts') },
      { find: '@holo-js/security', replacement: resolve(__dirname, '../security/src/index.ts') },
      { find: '@holo-js/auth', replacement: resolve(__dirname, '../auth/src/index.ts') },
      { find: '@holo-js/broadcast', replacement: resolve(__dirname, '../broadcast/src/index.ts') },
      { find: '@holo-js/cache', replacement: resolve(__dirname, '../cache/src/index.ts') },
      { find: '@holo-js/authorization', replacement: resolve(__dirname, '../authorization/src/index.ts') },
      { find: '@holo-js/auth-social', replacement: resolve(__dirname, '../auth-social/src/index.ts') },
      { find: '@holo-js/auth-workos', replacement: resolve(__dirname, '../auth-workos/src/index.ts') },
      { find: '@holo-js/auth-clerk', replacement: resolve(__dirname, '../auth-clerk/src/index.ts') },
      { find: '@holo-js/cache-db', replacement: resolve(__dirname, '../cache-db/src/index.ts') },
      { find: '@holo-js/config/registry', replacement: resolve(__dirname, '../config/src/registry.ts') },
      { find: '@holo-js/config', replacement: resolve(__dirname, '../config/src/index.ts') },
      { find: '@holo-js/core', replacement: resolve(__dirname, '../core/src/index.ts') },
      { find: '@holo-js/db', replacement: resolve(__dirname, '../db/src/index.ts') },
      { find: '@holo-js/db-mysql', replacement: resolve(__dirname, '../db-mysql/src/index.ts') },
      { find: '@holo-js/db-postgres', replacement: resolve(__dirname, '../db-postgres/src/index.ts') },
      { find: '@holo-js/db-sqlite', replacement: resolve(__dirname, '../db-sqlite/src/index.ts') },
      { find: '@holo-js/events', replacement: resolve(__dirname, '../events/src/index.ts') },
      { find: '@holo-js/kernel', replacement: resolve(__dirname, '../kernel/src/index.ts') },
      { find: '@holo-js/mail', replacement: resolve(__dirname, '../mail/src/index.ts') },
      { find: '@holo-js/media', replacement: resolve(__dirname, '../media/src/index.ts') },
      { find: '@holo-js/notifications', replacement: resolve(__dirname, '../notifications/src/index.ts') },
      { find: '@holo-js/queue', replacement: resolve(__dirname, '../queue/src/index.ts') },
      { find: '@holo-js/queue-redis', replacement: resolve(__dirname, '../queue-redis/src/index.ts') },
      { find: '@holo-js/queue-db', replacement: resolve(__dirname, '../queue-db/src/index.ts') },
      { find: '@holo-js/session', replacement: resolve(__dirname, '../session/src/index.ts') },
      { find: '@holo-js/storage-s3', replacement: resolve(__dirname, '../storage-s3/src/index.ts') },
      { find: '@holo-js/storage/runtime', replacement: resolve(__dirname, '../storage/src/runtime/composables/index.ts') },
      { find: '@holo-js/storage', replacement: resolve(__dirname, '../storage/src/index.ts') },
    ],
  },
  test: {
    name: '@holo-js/cli',
    environment: 'node',
    include: ['tests/**/*.test.ts'],
    maxWorkers: 2,
    testTimeout: includeCliIntegration ? 30_000 : 5_000,
    exclude: includeCliIntegration ? [] : ['tests/cli.test.ts'],
    coverage: {
      provider: 'v8',
      include: ['src/**/*.ts'],
      reportsDirectory: resolve(__dirname, '../../coverage/cli'),
      exclude: [
        'src/cli-types.ts',
        'src/**/types.ts',
        'src/bin/holo.ts',
        'src/bin/**',
        '**/src/bin/**',
        '**/node_modules/**',
      ],
    },
  },
})
